from __future__ import annotations

import unittest
from unittest.mock import Mock, patch

from test_support.postgres import TempPostgresMixin


class VideoVariantIndexSchemaTest(unittest.TestCase):
    def test_init_db_registers_variant_index_tables_and_indexes(self):
        from database import base

        executed: list[str] = []
        cursor = Mock()
        cursor.execute.side_effect = lambda sql, params=None: executed.append(str(sql))
        conn = Mock()
        conn.cursor.return_value = cursor

        with patch("database.base.get_db_orig", return_value=conn), \
            patch("database.translation.init_translation_db"), \
            patch("database.favorite.init_favorite_db"), \
            patch("translations.category_decensor.repair_masked_category_translations"), \
            patch("database.base._migrate_subscriptions"), \
            patch("database.base._create_index_if_possible") as create_index:
            base.init_db()

        joined = "\n".join(executed)
        self.assertIn("CREATE TABLE IF NOT EXISTS video_variant_groups", joined)
        self.assertIn("CREATE TABLE IF NOT EXISTS video_variant_group_items", joined)
        self.assertIn("CREATE TABLE IF NOT EXISTS video_variant_group_jobs", joined)
        self.assertIn("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", joined)
        index_sql = "\n".join(call.args[1] for call in create_index.call_args_list)
        self.assertIn("idx_video_variant_group_items_content_id", index_sql)
        self.assertIn("idx_video_variant_group_items_group_id", index_sql)
        self.assertIn("PRIMARY KEY(group_id, sort_rank)", joined)


class VideoVariantIndexDatabaseTest(TempPostgresMixin, unittest.TestCase):
    def _sample_groups(self) -> list[dict]:
        return [
            {
                "group_id": "MIAA-784",
                "canonical_code": "MIAA-784",
                "primary_content_id": "cid-1",
                "group_count": 2,
                "confidence": "high",
                "items": [
                    {
                        "content_id": "cid-1",
                        "dvd_id": "MIAA-784",
                        "display_code": "MIAA-784",
                        "service_code": "mono",
                        "variant_labels": ["uncensored", "4k"],
                        "sort_rank": 0,
                    },
                    {
                        "content_id": "cid-2",
                        "dvd_id": None,
                        "display_code": "MIAA-784-C",
                        "service_code": "digital",
                        "variant_labels": ["stream"],
                        "sort_rank": 1,
                    },
                ],
            }
        ]

    def test_replace_and_lookup_variant_groups_decode_labels(self):
        from database.video_variant_index import (
            get_variant_group_by_content_ids,
            replace_variant_groups,
            variant_group_stats,
        )

        result = replace_variant_groups(self._sample_groups())

        self.assertEqual(result, {"group_count": 1, "item_count": 2})
        by_content = get_variant_group_by_content_ids(["cid-1", "cid-2", "missing"])
        self.assertEqual(set(by_content), {"cid-1", "cid-2"})
        self.assertEqual(by_content["cid-1"]["group_id"], "MIAA-784")
        self.assertEqual(by_content["cid-1"]["items"][0]["variant_labels"], ["uncensored", "4k"])
        self.assertEqual(by_content["cid-1"]["items"][1]["service_code"], "digital")
        self.assertEqual(by_content["cid-2"]["primary_content_id"], "cid-1")
        stats = variant_group_stats()
        self.assertEqual(stats["group_count"], 1)
        self.assertEqual(stats["item_count"], 2)
        self.assertIsNotNone(stats["last_built_at"])

    def test_replace_variant_groups_allows_duplicate_content_ids_with_different_versions(self):
        from database.video_variant_index import get_variant_group_by_content_ids, replace_variant_groups

        replace_variant_groups(
            [
                {
                    "group_id": "MIAA-784",
                    "canonical_code": "MIAA-784",
                    "primary_content_id": "miaa00784",
                    "items": [
                        {"content_id": "miaa00784", "dvd_id": "MIAA-784", "display_code": "MIAA-784", "service_code": "mono", "sort_rank": 0},
                        {"content_id": "miaa00784", "dvd_id": None, "display_code": "MIAA-784", "service_code": "digital", "sort_rank": 1},
                    ],
                }
            ]
        )

        group = get_variant_group_by_content_ids(["miaa00784"])["miaa00784"]
        self.assertEqual(len(group["items"]), 2)
        self.assertEqual([item["service_code"] for item in group["items"]], ["mono", "digital"])

    def test_replace_variant_groups_keeps_old_index_when_insert_fails(self):
        from database.video_variant_index import get_variant_group_by_content_ids, replace_variant_groups

        replace_variant_groups(self._sample_groups())

        with self.assertRaises(Exception):
            replace_variant_groups(
                [
                    {
                        "group_id": "BROKEN",
                        "canonical_code": "BROKEN",
                        "primary_content_id": "cid-broken",
                        "items": [{"content_id": None}],
                    }
                ]
            )

        by_content = get_variant_group_by_content_ids(["cid-1"])
        self.assertEqual(by_content["cid-1"]["group_id"], "MIAA-784")

    def test_variant_group_jobs_round_trip_result_json_and_stats(self):
        from database.video_variant_index import (
            add_variant_group_job,
            get_variant_group_job,
            list_variant_group_jobs,
            update_variant_group_job,
            variant_group_stats,
        )

        job_id = add_variant_group_job()
        updated = update_variant_group_job(
            job_id,
            status="completed",
            total=3,
            processed=3,
            result={"group_count": 1, "item_count": 2},
        )

        self.assertIsNotNone(updated)
        self.assertEqual(updated["status"], "completed")
        self.assertEqual(updated["result"], {"group_count": 1, "item_count": 2})
        self.assertIsNone(update_variant_group_job(999999, status="missing"))
        self.assertEqual(get_variant_group_job(job_id)["result"]["item_count"], 2)
        self.assertEqual([job["id"] for job in list_variant_group_jobs(limit=1)], [job_id])
        self.assertEqual(variant_group_stats()["last_job"]["id"], job_id)


if __name__ == "__main__":
    unittest.main()
