from __future__ import annotations

import unittest

from test_support.postgres import TempPostgresMixin


class PlaybackProgressMovieLevelTests(TempPostgresMixin, unittest.TestCase):
    def test_online_progress_keeps_legacy_source_library(self):
        from database.playback import get_progress, list_continue_watching, save_progress

        save_progress(
            "M-ONLINE",
            source="online",
            resource_id=8,
            position_seconds=40,
            duration_seconds=100,
        )

        progress = get_progress("M-ONLINE")
        self.assertEqual(progress["source"], "library")
        self.assertEqual(progress["last_source"], "online")
        self.assertEqual(progress["last_resource_id"], 8)

        continue_rows = list_continue_watching()
        self.assertEqual(len(continue_rows), 1)
        self.assertEqual(continue_rows[0]["source"], "library")
        self.assertEqual(continue_rows[0]["last_source"], "online")

    def test_progress_is_movie_level_single_record(self):
        from database.base import get_db
        from database.playback import get_progress, save_progress

        save_progress(
            "M-1",
            source="online",
            resource_id=None,
            position_seconds=10,
            duration_seconds=100,
        )
        save_progress(
            "M-1",
            source="library",
            resource_id=7,
            position_seconds=55,
            duration_seconds=100,
        )

        progress = get_progress("M-1")
        self.assertEqual(progress["position_seconds"], 55)
        self.assertEqual(progress["last_source"], "library")
        self.assertEqual(progress["last_resource_id"], 7)
        self.assertEqual(progress["source"], "library")

        with get_db() as conn:
            cursor = conn.cursor()
            cursor.execute(
                "SELECT COUNT(*) AS count FROM playback_progress WHERE content_id = ?",
                ("M-1",),
            )
            self.assertEqual(cursor.fetchone()["count"], 1)

    def test_source_compatibility_argument_returns_same_movie_record(self):
        from database.playback import get_progress, save_progress

        save_progress(
            "M-1",
            source="online",
            resource_id=None,
            position_seconds=10,
            duration_seconds=100,
        )
        save_progress(
            "M-1",
            source="library",
            resource_id=7,
            position_seconds=55,
            duration_seconds=100,
        )

        progress = get_progress("M-1", source="online")
        self.assertEqual(progress["position_seconds"], 55)
        self.assertEqual(progress["last_source"], "library")
        self.assertEqual(progress["last_resource_id"], 7)

    def test_progress_map_only_queries_requested_movies_and_ignores_source_dimension(self):
        from database.playback import get_progress_map, save_progress

        save_progress("M-1", source="online", position_seconds=10, duration_seconds=100)
        save_progress(
            "M-1",
            source="library",
            resource_id=7,
            position_seconds=55,
            duration_seconds=100,
        )
        save_progress("M-2", source="library", position_seconds=33, duration_seconds=100)
        save_progress("OUTSIDE", source="online", position_seconds=44, duration_seconds=100)

        progress_map = get_progress_map(["M-1", "M-2", "M-1"], source="online")

        self.assertEqual(set(progress_map), {"M-1", "M-2"})
        self.assertEqual(progress_map["M-1"]["position_seconds"], 55)
        self.assertEqual(progress_map["M-1"]["last_source"], "library")
        self.assertEqual(progress_map["M-2"]["last_source"], "library")

    def test_old_source_unique_schema_migrates_to_latest_movie_record_idempotently(self):
        from database import base

        conn = base.get_db_orig()
        try:
            cursor = conn.cursor()
            cursor.execute("DROP TABLE playback_progress")
            cursor.execute(
                """
                CREATE TABLE playback_progress (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    content_id TEXT NOT NULL,
                    user_id TEXT,
                    source TEXT NOT NULL DEFAULT 'library',
                    position_seconds DOUBLE PRECISION DEFAULT 0,
                    duration_seconds DOUBLE PRECISION DEFAULT 0,
                    completed INTEGER DEFAULT 0,
                    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(content_id, source)
                )
                """
            )
            cursor.execute(
                """
                INSERT INTO playback_progress (
                    content_id, source, position_seconds, duration_seconds, completed, updated_at
                )
                VALUES
                    ('M-OLD', 'online', 10, 100, 0, '2026-06-14T10:00:00+08:00'),
                    ('M-OLD', 'library', 65, 100, 0, '2026-06-14T11:00:00+08:00'),
                    ('M-ONLINE', 'library', 15, 100, 0, '2026-06-14T09:00:00+08:00'),
                    ('M-ONLINE', 'online', 70, 100, 0, '2026-06-14T13:00:00+08:00'),
                    ('M-TIE', 'online', 20, 100, 0, '2026-06-14T12:00:00+08:00'),
                    ('M-TIE', 'library', 75, 100, 0, '2026-06-14T12:00:00+08:00')
                """
            )
            conn.commit()

            base._init_playback_tables(cursor)
            conn.commit()
            base._init_playback_tables(cursor)
            conn.commit()

            cursor.execute(
                """
                SELECT content_id, source, last_source, last_resource_id, position_seconds
                FROM playback_progress
                ORDER BY content_id
                """
            )
            rows = [dict(row) for row in cursor.fetchall()]
            self.assertEqual(
                rows,
                [
                    {
                        "content_id": "M-OLD",
                        "source": "library",
                        "last_source": "library",
                        "last_resource_id": None,
                        "position_seconds": 65.0,
                    },
                    {
                        "content_id": "M-ONLINE",
                        "source": "library",
                        "last_source": "online",
                        "last_resource_id": None,
                        "position_seconds": 70.0,
                    },
                    {
                        "content_id": "M-TIE",
                        "source": "library",
                        "last_source": "library",
                        "last_resource_id": None,
                        "position_seconds": 75.0,
                    },
                ],
            )

            cursor.execute(
                """
                SELECT
                    tc.constraint_name,
                    string_agg(kcu.column_name, ',' ORDER BY kcu.ordinal_position) AS columns
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                  ON tc.constraint_name = kcu.constraint_name
                 AND tc.table_schema = kcu.table_schema
                 AND tc.table_name = kcu.table_name
                WHERE tc.table_schema = current_schema()
                  AND tc.table_name = 'playback_progress'
                  AND tc.constraint_type = 'UNIQUE'
                GROUP BY tc.constraint_name
                """
            )
            constraints = [dict(row) for row in cursor.fetchall()]
            self.assertEqual(len(constraints), 1)
            self.assertEqual(constraints[0]["columns"], "content_id")
        finally:
            conn.close()

    def test_migration_survives_wrong_index_using_preferred_constraint_name(self):
        from database import base
        from database.playback import get_progress, save_progress

        conn = base.get_db_orig()
        try:
            cursor = conn.cursor()
            cursor.execute("DROP TABLE playback_progress")
            cursor.execute(
                """
                CREATE TABLE playback_progress (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    content_id TEXT NOT NULL,
                    user_id TEXT,
                    source TEXT NOT NULL DEFAULT 'library',
                    position_seconds DOUBLE PRECISION DEFAULT 0,
                    duration_seconds DOUBLE PRECISION DEFAULT 0,
                    completed INTEGER DEFAULT 0,
                    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(content_id, source)
                )
                """
            )
            cursor.execute(
                """
                CREATE INDEX playback_progress_content_id_key
                ON playback_progress(source)
                """
            )
            conn.commit()

            base._init_playback_tables(cursor)
            conn.commit()
        finally:
            conn.close()

        save_progress("M-COLLIDE", source="online", position_seconds=10, duration_seconds=100)
        save_progress("M-COLLIDE", source="library", position_seconds=60, duration_seconds=100)

        progress = get_progress("M-COLLIDE")
        self.assertEqual(progress["position_seconds"], 60)
        with base.get_db() as check_conn:
            cursor = check_conn.cursor()
            cursor.execute(
                """
                SELECT COUNT(*) AS count
                FROM playback_progress
                WHERE content_id = ?
                """,
                ("M-COLLIDE",),
            )
            self.assertEqual(cursor.fetchone()["count"], 1)
            cursor.execute(
                """
                SELECT COUNT(*) AS count
                FROM pg_index index_info
                JOIN pg_class table_info
                  ON table_info.oid = index_info.indrelid
                JOIN pg_namespace table_namespace
                  ON table_namespace.oid = table_info.relnamespace
                WHERE table_namespace.nspname = current_schema()
                  AND table_info.relname = 'playback_progress'
                  AND index_info.indisunique
                  AND index_info.indpred IS NULL
                  AND index_info.indexprs IS NULL
                  AND index_info.indnkeyatts = 1
                  AND (
                      SELECT array_agg(attribute.attname ORDER BY key_column.ordinality)
                      FROM unnest(index_info.indkey)
                          WITH ORDINALITY AS key_column(attribute_number, ordinality)
                      JOIN pg_attribute attribute
                        ON attribute.attrelid = table_info.oid
                       AND attribute.attnum = key_column.attribute_number
                  ) = ARRAY['content_id']::name[]
                """
            )
            self.assertEqual(cursor.fetchone()["count"], 1)


if __name__ == "__main__":
    unittest.main()
