from __future__ import annotations

import unittest
from types import SimpleNamespace
from unittest.mock import Mock, patch


class PostgresDatabaseLayerTest(unittest.TestCase):
    def test_get_db_orig_uses_javhub_database_config(self):
        from database import base

        cfg = SimpleNamespace(
            javhub_database={
                "host": "state-postgres",
                "port": 25432,
                "database": "javhub",
                "user": "javhub-user",
                "password": "secret",
            }
        )
        conn = Mock()

        with patch("database.base.config", cfg), patch("database.base.psycopg2.connect", return_value=conn) as connect:
            wrapped = base.get_db_orig()

        self.assertIs(wrapped._conn, conn)

        connect.assert_called_once_with(
            host="state-postgres",
            port=25432,
            dbname="javhub",
            user="javhub-user",
            password="secret",
            cursor_factory=base.RealDictCursor,
        )

    def test_init_db_uses_idempotent_postgres_schema(self):
        from database import base

        executed: list[str] = []
        cursor = Mock()
        cursor.execute.side_effect = lambda sql, params=None: executed.append(str(sql))
        conn = Mock()
        conn.cursor.return_value = cursor

        with patch("database.base.get_db_orig", return_value=conn), \
            patch("database.translation.init_translation_db"), \
            patch("database.favorite.init_favorite_db"), \
            patch("translations.category_decensor.repair_masked_category_translations"), \
            patch("database.base._create_indexes") as create_indexes:
            base.init_db()
            base.init_db()

        joined = "\n".join(executed)
        self.assertIn("CREATE TABLE IF NOT EXISTS download_tasks", joined)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", joined)
        self.assertIn("ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS last_check", joined)
        self.assertNotIn("AUTOINCREMENT", joined)
        self.assertNotIn("PRAGMA", joined)
        self.assertGreaterEqual(conn.commit.call_count, 2)
        self.assertGreaterEqual(conn.close.call_count, 2)
        self.assertEqual(create_indexes.call_count, 2)


if __name__ == "__main__":
    unittest.main()
