export const DEFAULT_CONFIG = {
  openlist: { api_url: '', username: '', password: '', default_path: '/115/AV' },
  downloaders: { default_id: 'openlist', clients: [] },
  emby: { api_url: '', api_key: '' },
  telegram: { bot_token: '', allowed_user_ids: [] },
  crawler: { request_interval: 3 },
  scheduler: { subscription_check_hour: 2 },
  automation: {
    download_policy: 'manual',
    candidate_sources: ['subscription', 'inventory', 'supplement'],
    rules_require_magnet: true,
    auto_process_interval_minutes: 30,
    max_auto_downloads_per_run: 20,
    max_auto_downloads_per_24h: 100,
  },
  actor_mapping: {
    auto_match_after_collect: true,
    auto_confirm_policy: 'conservative',
    candidate_per_actor: 3,
    candidate_min_confidence: 0.55,
    auto_confirm_confidence: 0.98,
    auto_confirm_gap: 0.08,
  },
  notification: { enabled: false, telegram: true, auto_download_notify: true, download_complete_notify: true, new_movie_notify: true },
  javinfo: {
    api_url: 'http://localhost:18080',
    page_size: 30,
    timeout: 30,
    import_db: {
      host: 'localhost',
      port: 5432,
      database: 'r18',
      maintenance_database: 'postgres',
      user: 'kongmei',
      password: '',
      max_parallel_jobs: 2,
      keep_previous_databases: 1,
    },
  },
  ai: {
    provider: 'openai_compatible',
    openai_compatible: {
      base_url: 'https://api.openai.com/v1',
      api_key: '',
      model: 'gpt-4o-mini',
      timeout: 30,
    },
    gemini: {
      base_url: 'https://generativelanguage.googleapis.com/v1beta',
      api_key: '',
      model: 'gemini-2.0-flash',
      timeout: 30,
    },
    ollama: {
      base_url: 'http://localhost:11434',
      api_key: '',
      model: '',
      timeout: 30,
    },
  },
  translation: {
    enabled: true,
    target_language: 'zh-CN',
    provider_order: ['cache', 'mapping', 'google_free', 'deepl', 'microsoft', 'openai_compatible'],
    batch_provider_order: ['cache', 'mapping', 'google_free', 'deepl', 'microsoft'],
    realtime_mode: 'cache_only',
    batch_concurrency: 32,
    batch_size: 200,
    batch_char_limit: 24000,
    source_page_size: 500,
    scan_pages_per_batch: 8,
    google_free: {
      enabled: true,
      base_url: 'https://translate.googleapis.com/translate_a/single',
      timeout: 10,
    },
    deepl: {
      enabled: false,
      api_key: '',
      free_api: true,
      timeout: 15,
    },
    microsoft: {
      enabled: false,
      api_key: '',
      region: '',
      endpoint: 'https://api.cognitive.microsofttranslator.com',
      timeout: 15,
    },
  },
  proxy: { enabled: false, http_url: '', https_url: '' },
  server: { frontend_origin: 'http://localhost:5174' },
  rate_limit: { enabled: false, requests_per_minute: 60, burst: 10 },
}

export const DEFAULT_BUBBLE_CFG = {
  baseSize: 16, fillPercent: 50, spacing: 16,
  bubbleCount: 36,
  defaultTab: 'genre',
  actressAvatarSize: 'medium',
  actressPageSize: 36,
  seriesPageSize: 24,
}

export const TRANSLATION_TYPE_LABELS = { actress: '演员', category: '题材', series: '系列', maker: '厂商', label: '厂牌', title: '标题' }
