"""PostgreSQL connection and schema initialization."""
from __future__ import annotations

import re
import threading
from contextlib import contextmanager
from datetime import date, datetime
from typing import Any, Iterable

import psycopg2
from psycopg2 import sql
from psycopg2 import pool as _pg_pool
from psycopg2.extras import RealDictCursor

from config import config


_IDENTITY_TABLES = {
    "actor_aliases",
    "actor_mappings",
    "actress_missing_summary",
    "candidate_process_runs",
    "collections",
    "download_candidate_events",
    "download_candidates",
    "download_tasks",
    "emby_snapshots",
    "exempt_videos",
    "ignored_duplicates",
    "inventory_jobs",
    "library_files",
    "library_scan_runs",
    "logs",
    "movie_resources",
    "playback_progress",
    "subscriptions",
    "translation_cache",
    "translation_jobs",
    "translation_workbench_history",
    "translation_workbench_items",
    "video_variant_group_jobs",
}


class CompatRow(dict):
    """Dict row that also supports legacy sqlite-style integer indexing."""

    def __init__(self, data: dict[str, Any]):
        super().__init__(data)
        self._columns = list(data.keys())

    def __getitem__(self, key: Any) -> Any:
        if isinstance(key, int):
            return super().__getitem__(self._columns[key])
        return super().__getitem__(key)


class CompatCursor:
    def __init__(self, cursor: Any):
        self._cursor = cursor
        self.lastrowid: int | None = None

    @property
    def rowcount(self) -> int:
        return int(getattr(self._cursor, "rowcount", -1))

    def execute(self, query: str, params: Iterable[Any] | None = None):
        prepared, values, capture_id = _prepare_sql(query, params)
        self.lastrowid = None
        self._cursor.execute(prepared, values)
        if capture_id and self.rowcount > 0:
            row = self._cursor.fetchone()
            if row:
                self.lastrowid = int(row.get("id") if isinstance(row, dict) else row[0])
        return self

    def executemany(self, query: str, seq_of_params: Iterable[Iterable[Any]]):
        prepared, _values, _capture_id = _prepare_sql(query, None, capture_identity=False)
        self.lastrowid = None
        self._cursor.executemany(prepared, [_normalize_params(params) for params in seq_of_params])
        return self

    def fetchone(self):
        return _wrap_row(self._cursor.fetchone())

    def fetchall(self):
        return [_wrap_row(row) for row in self._cursor.fetchall()]

    def close(self) -> None:
        self._cursor.close()

    def __getattr__(self, name: str) -> Any:
        return getattr(self._cursor, name)


class CompatConnection:
    def __init__(self, conn: Any, pooled: bool = False, pool: Any = None):
        self._conn = conn
        self._pooled = pooled
        self._pool = pool
        self._released = False

    def cursor(self, *args: Any, **kwargs: Any) -> CompatCursor:
        return CompatCursor(self._conn.cursor(*args, **kwargs))

    def execute(self, query: str, params: Iterable[Any] | None = None) -> CompatCursor:
        cursor = self.cursor()
        cursor.execute(query, params)
        return cursor

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        # Idempotent: return pooled connections to the pool instead of closing
        # the socket; close plain (fallback) connections normally.
        if self._released:
            return
        self._released = True
        _release_connection(self._conn, self._pooled, self._pool)

    def __getattr__(self, name: str) -> Any:
        return getattr(self._conn, name)


def _wrap_row(row: Any):
    if row is None:
        return None
    if isinstance(row, CompatRow):
        return row
    if isinstance(row, dict):
        return CompatRow({key: _normalize_value(value) for key, value in dict(row).items()})
    return row


def _normalize_value(value: Any) -> Any:
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, date):
        return value.isoformat()
    return value


def _normalize_params(params: Iterable[Any] | None):
    if params is None:
        return None
    return tuple(1 if value is True else 0 if value is False else value for value in params)


def _prepare_sql(
    query: str,
    params: Iterable[Any] | None,
    *,
    capture_identity: bool = True,
) -> tuple[str, Iterable[Any] | None, bool]:
    text = str(query).strip()
    text = re.sub(
        r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        text,
        flags=re.IGNORECASE,
    )
    text = re.sub(
        r"\b(TEXT)\s+DEFAULT\s+CURRENT_TIMESTAMP\b",
        "TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP",
        text,
        flags=re.IGNORECASE,
    )
    text = re.sub(
        r"\bALTER\s+TABLE\s+([^\s]+)\s+ADD\s+COLUMN\s+(?!IF\s+NOT\s+EXISTS)",
        r"ALTER TABLE \1 ADD COLUMN IF NOT EXISTS ",
        text,
        flags=re.IGNORECASE,
    )
    text = re.sub(r"\bIS\s+\?", "IS NOT DISTINCT FROM ?", text, flags=re.IGNORECASE)
    text = re.sub(
        r"datetime\('now',\s*\?\)",
        "(CURRENT_TIMESTAMP + ?::interval)",
        text,
        flags=re.IGNORECASE,
    )

    insert_ignore = bool(re.match(r"INSERT\s+OR\s+IGNORE\s+INTO\b", text, re.IGNORECASE))
    if insert_ignore:
        text = re.sub(r"^INSERT\s+OR\s+IGNORE\s+INTO", "INSERT INTO", text, flags=re.IGNORECASE)
        if " ON CONFLICT " not in text.upper():
            text = text.rstrip(";") + " ON CONFLICT DO NOTHING"

    capture_id = False
    table = _insert_table(text)
    if capture_identity and table in _IDENTITY_TABLES and " RETURNING " not in text.upper():
        text = text.rstrip(";") + " RETURNING id"
        capture_id = True

    text = text.replace("?", "%s")
    return text, _normalize_params(params), capture_id


def _insert_table(query: str) -> str | None:
    match = re.match(r"INSERT\s+INTO\s+([A-Za-z_][A-Za-z0-9_]*)\b", query.strip(), re.IGNORECASE)
    return match.group(1).lower() if match else None


def _database_exists(settings: dict[str, Any]) -> bool:
    maintenance = str(settings.get("maintenance_database") or "postgres")
    conn = psycopg2.connect(
        host=settings["host"],
        port=settings["port"],
        dbname=maintenance,
        user=settings["user"],
        password=settings["password"],
        cursor_factory=RealDictCursor,
    )
    try:
        conn.autocommit = True
        with conn.cursor() as cursor:
            cursor.execute("SELECT 1 FROM pg_database WHERE datname = %s", (settings["database"],))
            return cursor.fetchone() is not None
    finally:
        conn.close()


def ensure_database() -> None:
    settings = config.javhub_database
    if _database_exists(settings):
        return
    maintenance = str(settings.get("maintenance_database") or "postgres")
    conn = psycopg2.connect(
        host=settings["host"],
        port=settings["port"],
        dbname=maintenance,
        user=settings["user"],
        password=settings["password"],
        cursor_factory=RealDictCursor,
    )
    try:
        conn.autocommit = True
        with conn.cursor() as cursor:
            cursor.execute(
                sql.SQL("CREATE DATABASE {}").format(sql.Identifier(settings["database"]))
            )
    finally:
        conn.close()


# === Connection pool ===========================================================
# Every DB call used to open a brand-new psycopg2 connection and tear it down
# afterwards. Across a compare/process run that is thousands of TCP+auth
# round-trips that block whatever loop/thread is driving the job. A process-wide
# ThreadedConnectionPool reuses connections instead. Pooling is best-effort: if
# the pool can't be built or is momentarily exhausted, we transparently fall
# back to a direct connection so the app never hard-fails on a pool error.

_pool: _pg_pool.ThreadedConnectionPool | None = None
_pool_key: tuple | None = None
_pool_lock = threading.Lock()


def _settings_key(settings: dict) -> tuple:
    return (settings["host"], settings["port"], settings["database"], settings["user"])


def _connect_direct() -> Any:
    """Open a single raw psycopg2 connection (creating the DB on first use)."""
    settings = config.javhub_database
    kwargs = dict(
        host=settings["host"],
        port=settings["port"],
        dbname=settings["database"],
        user=settings["user"],
        password=settings["password"],
        cursor_factory=RealDictCursor,
    )
    try:
        return psycopg2.connect(**kwargs)
    except psycopg2.OperationalError as exc:
        if f'database "{settings["database"]}" does not exist' not in str(exc):
            raise
        ensure_database()
        return psycopg2.connect(**kwargs)


def _create_pool() -> _pg_pool.ThreadedConnectionPool:
    settings = config.javhub_database
    maxconn = int(settings.get("pool_max") or 32)
    kwargs = dict(
        host=settings["host"],
        port=settings["port"],
        dbname=settings["database"],
        user=settings["user"],
        password=settings["password"],
        cursor_factory=RealDictCursor,
    )
    try:
        return _pg_pool.ThreadedConnectionPool(1, maxconn, **kwargs)
    except psycopg2.OperationalError as exc:
        if f'database "{settings["database"]}" does not exist' not in str(exc):
            raise
        ensure_database()
        return _pg_pool.ThreadedConnectionPool(1, maxconn, **kwargs)


def _get_pool() -> _pg_pool.ThreadedConnectionPool | None:
    """Return the pool for the *current* DB settings, rebuilding on change.

    Keying by settings keeps test isolation intact: each test repoints config at
    a fresh temp database via ``config.reload()``, and a stale pool bound to a
    previous (possibly dropped) database must not keep serving connections.
    """
    global _pool, _pool_key
    key = _settings_key(config.javhub_database)
    if _pool is not None and _pool_key == key:
        return _pool
    with _pool_lock:
        if _pool is not None and _pool_key == key:
            return _pool
        if _pool is not None:
            try:
                _pool.closeall()
            except Exception:
                pass
            _pool = None
            _pool_key = None
        try:
            _pool = _create_pool()
            _pool_key = key
        except Exception:
            _pool = None  # pooling unavailable → direct connections
            _pool_key = None
    return _pool


def _release_connection(raw: Any, pooled: bool, pool: Any = None) -> None:
    if pooled and pool is not None:
        try:
            if not getattr(raw, "closed", False):
                # Reset any open/aborted transaction before reuse so the next
                # borrower never inherits a dirty session.
                raw.rollback()
            pool.putconn(raw)
            return
        except Exception:
            try:
                raw.close()
            except Exception:
                pass
            return
    try:
        raw.close()
    except Exception:
        pass


def get_db_orig():
    """Return a PostgreSQL connection wrapper for JavHub state.

    Borrows from the shared pool when available; falls back to a fresh direct
    connection if the pool is unavailable or exhausted.
    """
    pool = _get_pool()
    if pool is not None:
        try:
            return CompatConnection(pool.getconn(), pooled=True, pool=pool)
        except _pg_pool.PoolError:
            pass  # exhausted/closed → degrade gracefully to a direct connection
    return CompatConnection(_connect_direct(), pooled=False)


@contextmanager
def get_db():
    """Database connection context manager with commit/rollback/close."""
    conn = get_db_orig()
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def _add_column_if_missing(cursor, sql_text: str) -> None:
    cursor.execute(sql_text)


def _create_index_if_possible(cursor, sql_text: str) -> None:
    cursor.execute(sql_text)


def init_db():
    """Initialize all PostgreSQL tables used by JavHub state."""
    _init_translation_and_favorites()

    conn = get_db_orig()
    try:
        cursor = conn.cursor()
        _init_core_state_tables(cursor)
        _init_inventory_tables(cursor)
        _init_actor_mapping_tables(cursor)
        _init_download_candidate_tables(cursor)
        _init_video_variant_tables(cursor)
        _init_emby_snapshot_tables(cursor)
        _init_library_tables(cursor)
        _init_movie_resource_tables(cursor)
        conn.commit()
    finally:
        conn.close()

    _migrate_subscriptions()
    _create_indexes()


def _init_translation_and_favorites() -> None:
    from database.translation import init_translation_db
    init_translation_db()
    from translations.category_decensor import repair_masked_category_translations
    repair_masked_category_translations()
    from database.favorite import init_favorite_db
    init_favorite_db()


def _init_core_state_tables(cursor) -> None:
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS download_tasks (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            content_id TEXT,
            title TEXT,
            magnet TEXT,
            path TEXT,
            downloader_id TEXT,
            downloader_name TEXT,
            downloader_type TEXT,
            remote_task_id TEXT,
            status TEXT DEFAULT 'pending',
            error_msg TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ
        )
    ''')
    for sql_text in (
        "ALTER TABLE download_tasks ADD COLUMN IF NOT EXISTS downloader_id TEXT",
        "ALTER TABLE download_tasks ADD COLUMN IF NOT EXISTS downloader_name TEXT",
        "ALTER TABLE download_tasks ADD COLUMN IF NOT EXISTS downloader_type TEXT",
        "ALTER TABLE download_tasks ADD COLUMN IF NOT EXISTS remote_task_id TEXT",
        "ALTER TABLE download_tasks ADD COLUMN IF NOT EXISTS movie_id TEXT",
        "ALTER TABLE download_tasks ADD COLUMN IF NOT EXISTS info_hash TEXT",
        "ALTER TABLE download_tasks ADD COLUMN IF NOT EXISTS target_folder_id TEXT",
        "ALTER TABLE download_tasks ADD COLUMN IF NOT EXISTS open115_task_id TEXT",
        "ALTER TABLE download_tasks ADD COLUMN IF NOT EXISTS result_file_id TEXT",
    ):
        _add_column_if_missing(cursor, sql_text)

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS subscriptions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            actress_id INTEGER,
            actress_name TEXT NOT NULL,
            enabled INTEGER DEFAULT 1,
            auto_download INTEGER DEFAULT 0,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            last_check TIMESTAMPTZ,
            last_found TEXT
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS logs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            level TEXT,
            message TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS ignored_duplicates (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            content_id TEXT,
            emby_item_id TEXT NOT NULL,
            ignored_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            reason TEXT
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS actress_missing_summary (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            actress_id INTEGER NOT NULL UNIQUE,
            actress_name TEXT NOT NULL,
            total_in_javinfo INTEGER,
            missing_count INTEGER,
            missing_videos_json TEXT,
            last_updated TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
    ''')


def _init_inventory_tables(cursor) -> None:
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS inventory_jobs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_type TEXT NOT NULL,
            actor_id INTEGER,
            snapshot_key TEXT,
            status TEXT DEFAULT 'pending',
            error_msg TEXT,
            result_json TEXT,
            progress INTEGER DEFAULT 0,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ
        )
    ''')
    for sql_text in (
        "ALTER TABLE inventory_jobs ADD COLUMN IF NOT EXISTS snapshot_key TEXT",
        "ALTER TABLE inventory_jobs ADD COLUMN IF NOT EXISTS progress INTEGER DEFAULT 0",
        "ALTER TABLE inventory_jobs ADD COLUMN IF NOT EXISTS result_json TEXT",
    ):
        _add_column_if_missing(cursor, sql_text)

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS inventory_actors (
            actress_id INTEGER PRIMARY KEY,
            actress_name TEXT NOT NULL,
            normalized_id INTEGER,
            primary_name TEXT,
            total_videos INTEGER DEFAULT 0,
            missing_count INTEGER DEFAULT 0,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS inventory_videos (
            content_id TEXT PRIMARY KEY,
            emby_item_id TEXT NOT NULL,
            actress_id INTEGER NOT NULL,
            title TEXT,
            release_date TEXT,
            jacket_thumb_url TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS missing_videos (
            content_id TEXT PRIMARY KEY,
            actress_id INTEGER NOT NULL,
            title TEXT,
            release_date TEXT,
            jacket_thumb_url TEXT,
            source TEXT DEFAULT 'javinfo',
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS exempt_videos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            content_id TEXT UNIQUE NOT NULL,
            actress_id INTEGER,
            reason TEXT,
            created_by TEXT DEFAULT 'manual',
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
    ''')


def _init_actor_mapping_tables(cursor) -> None:
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS actor_aliases (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            alias_id INTEGER NOT NULL,
            canonical_id INTEGER NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS actor_mappings (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            emby_actor_id TEXT NOT NULL,
            emby_actor_name TEXT NOT NULL,
            javinfo_actress_id INTEGER,
            javinfo_actress_name TEXT,
            confidence REAL DEFAULT 0,
            status TEXT DEFAULT 'candidate',
            source TEXT DEFAULT 'manual',
            javinfo_avatar_url TEXT,
            movie_count INTEGER,
            confidence_breakdown_json TEXT,
            confidence_label TEXT,
            risk_flags_json TEXT,
            ai_decision TEXT,
            ai_confidence REAL,
            ai_reason TEXT,
            ai_model TEXT,
            ai_reviewed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ
        )
    ''')
    for sql_text in (
        "ALTER TABLE actor_mappings ADD COLUMN IF NOT EXISTS javinfo_avatar_url TEXT",
        "ALTER TABLE actor_mappings ADD COLUMN IF NOT EXISTS movie_count INTEGER",
        "ALTER TABLE actor_mappings ADD COLUMN IF NOT EXISTS confidence_breakdown_json TEXT",
        "ALTER TABLE actor_mappings ADD COLUMN IF NOT EXISTS confidence_label TEXT",
        "ALTER TABLE actor_mappings ADD COLUMN IF NOT EXISTS risk_flags_json TEXT",
        "ALTER TABLE actor_mappings ADD COLUMN IF NOT EXISTS ai_decision TEXT",
        "ALTER TABLE actor_mappings ADD COLUMN IF NOT EXISTS ai_confidence REAL",
        "ALTER TABLE actor_mappings ADD COLUMN IF NOT EXISTS ai_reason TEXT",
        "ALTER TABLE actor_mappings ADD COLUMN IF NOT EXISTS ai_model TEXT",
        "ALTER TABLE actor_mappings ADD COLUMN IF NOT EXISTS ai_reviewed_at TIMESTAMPTZ",
    ):
        _add_column_if_missing(cursor, sql_text)
    cursor.execute('''
        CREATE UNIQUE INDEX IF NOT EXISTS idx_actor_mappings_pair
        ON actor_mappings(emby_actor_id, javinfo_actress_id)
    ''')


def _init_download_candidate_tables(cursor) -> None:
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS download_candidates (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            content_id TEXT NOT NULL,
            dvd_id TEXT,
            title TEXT,
            actress_id INTEGER,
            actress_name TEXT,
            jacket_thumb_url TEXT,
            release_date TEXT,
            source TEXT DEFAULT 'manual',
            reason TEXT,
            status TEXT DEFAULT 'candidate',
            magnet TEXT,
            magnet_source TEXT,
            download_task_id INTEGER,
            error_msg TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ
        )
    ''')
    _add_column_if_missing(cursor, "ALTER TABLE download_candidates ADD COLUMN IF NOT EXISTS error_msg TEXT")
    cursor.execute('''
        CREATE UNIQUE INDEX IF NOT EXISTS idx_download_candidates_content_source
        ON download_candidates(content_id, source)
    ''')
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS download_candidate_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            candidate_id INTEGER NOT NULL,
            action TEXT NOT NULL,
            detail TEXT,
            operator TEXT DEFAULT 'system',
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
    ''')
    cursor.execute('''
        CREATE INDEX IF NOT EXISTS idx_download_candidate_events_candidate
        ON download_candidate_events(candidate_id, created_at DESC)
    ''')
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS candidate_process_runs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            trigger_source TEXT DEFAULT 'manual',
            policy TEXT,
            status TEXT DEFAULT 'completed',
            filters_json TEXT,
            result_json TEXT,
            total INTEGER DEFAULT 0,
            sent INTEGER DEFAULT 0,
            failed INTEGER DEFAULT 0,
            skipped INTEGER DEFAULT 0,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
    ''')
    cursor.execute('''
        CREATE INDEX IF NOT EXISTS idx_candidate_process_runs_created
        ON candidate_process_runs(created_at DESC)
    ''')


def _init_video_variant_tables(cursor) -> None:
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS video_variant_groups (
            group_id TEXT PRIMARY KEY,
            canonical_code TEXT,
            primary_content_id TEXT,
            group_count INTEGER,
            confidence TEXT,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
    ''')
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS video_variant_group_items (
            group_id TEXT,
            content_id TEXT NOT NULL,
            dvd_id TEXT,
            display_code TEXT,
            service_code TEXT,
            variant_labels_json TEXT,
            sort_rank INTEGER,
            PRIMARY KEY(group_id, sort_rank)
        )
    ''')
    cursor.execute('''
        DO $$
        DECLARE
            pk_name TEXT;
            pk_cols TEXT;
        BEGIN
            SELECT tc.constraint_name, string_agg(kcu.column_name, ',' ORDER BY kcu.ordinal_position)
            INTO pk_name, pk_cols
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
            WHERE tc.table_schema = current_schema()
              AND tc.table_name = 'video_variant_group_items'
              AND tc.constraint_type = 'PRIMARY KEY'
            GROUP BY tc.constraint_name;

            IF pk_cols = 'group_id,content_id' THEN
                EXECUTE format('ALTER TABLE video_variant_group_items DROP CONSTRAINT %I', pk_name);
            END IF;

            IF pk_cols IS NULL OR pk_cols = 'group_id,content_id' THEN
                ALTER TABLE video_variant_group_items
                ADD CONSTRAINT video_variant_group_items_pkey PRIMARY KEY(group_id, sort_rank);
            END IF;

            ALTER TABLE video_variant_group_items ALTER COLUMN content_id SET NOT NULL;
        END $$;
    ''')
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS video_variant_group_jobs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            status TEXT,
            total INTEGER DEFAULT 0,
            processed INTEGER DEFAULT 0,
            result_json TEXT,
            error TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
    ''')


def _init_emby_snapshot_tables(cursor) -> None:
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS emby_snapshots (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            snapshot_key TEXT NOT NULL,
            actress_id INTEGER NOT NULL,
            actress_name TEXT NOT NULL,
            emby_item_id TEXT NOT NULL,
            title TEXT,
            filename TEXT,
            collected_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS emby_actors (
            actress_id INTEGER PRIMARY KEY,
            actress_name TEXT NOT NULL,
            total_videos INTEGER DEFAULT 0,
            image_tag TEXT,
            snapshot_key TEXT,
            updated_at TIMESTAMPTZ
        )
    ''')
    _add_column_if_missing(cursor, "ALTER TABLE emby_actors ADD COLUMN IF NOT EXISTS image_tag TEXT")


def _init_library_tables(cursor) -> None:
    """自有云盘文件索引 + 播放进度（去 Emby 化，见 docs/superpowers/plans/2026-06-12-library-index-player.md）。

    约束：library_files 只存引用（backend+path+ref_payload），任何直链都不允许入库。
    """
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS library_files (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            backend TEXT NOT NULL DEFAULT 'openlist',
            path TEXT NOT NULL,
            name TEXT NOT NULL,
            size BIGINT DEFAULT 0,
            modified_at TEXT,
            content_id TEXT,
            match_status TEXT DEFAULT 'unmatched',
            ref_payload TEXT,
            first_seen_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            last_seen_at TIMESTAMPTZ,
            deleted_at TIMESTAMPTZ,
            UNIQUE(backend, path)
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS library_scan_runs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            mode TEXT NOT NULL,
            root_path TEXT,
            status TEXT DEFAULT 'running',
            files_seen INTEGER DEFAULT 0,
            files_added INTEGER DEFAULT 0,
            files_removed INTEGER DEFAULT 0,
            files_matched INTEGER DEFAULT 0,
            error TEXT,
            started_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            finished_at TIMESTAMPTZ
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS playback_progress (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            content_id TEXT NOT NULL,
            user_id TEXT,
            source TEXT NOT NULL DEFAULT 'library',
            position_seconds DOUBLE PRECISION DEFAULT 0,
            duration_seconds DOUBLE PRECISION DEFAULT 0,
            completed INTEGER DEFAULT 0,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(content_id, source)
        )
    ''')


def _init_movie_resource_tables(cursor) -> None:
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS movie_resources (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            movie_id TEXT NOT NULL,
            provider TEXT NOT NULL DEFAULT 'open115',
            remote_file_id TEXT NOT NULL,
            parent_id TEXT,
            pick_code TEXT,
            name TEXT NOT NULL,
            extension TEXT,
            size BIGINT DEFAULT 0,
            duration BIGINT DEFAULT 0,
            resource_type TEXT NOT NULL DEFAULT 'video',
            status TEXT NOT NULL DEFAULT 'pending',
            is_default INTEGER NOT NULL DEFAULT 0,
            download_task_id INTEGER,
            related_resource_id INTEGER,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(provider, remote_file_id),
            CHECK (resource_type IN ('video', 'subtitle')),
            CHECK (status IN ('pending', 'ready', 'missing', 'failed'))
        )
    ''')


def _create_indexes():
    """Create common PostgreSQL indexes."""
    conn = get_db_orig()
    cursor = conn.cursor()
    indexes = [
        "CREATE INDEX IF NOT EXISTS idx_library_files_content ON library_files(content_id)",
        "CREATE INDEX IF NOT EXISTS idx_library_files_status ON library_files(match_status)",
        "CREATE INDEX IF NOT EXISTS idx_library_files_seen ON library_files(last_seen_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_playback_progress_updated ON playback_progress(updated_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_download_tasks_status ON download_tasks(status)",
        "CREATE INDEX IF NOT EXISTS idx_download_tasks_content_id ON download_tasks(content_id)",
        "CREATE INDEX IF NOT EXISTS idx_download_tasks_movie_id ON download_tasks(movie_id)",
        "CREATE INDEX IF NOT EXISTS idx_download_tasks_info_hash ON download_tasks(info_hash)",
        "CREATE INDEX IF NOT EXISTS idx_download_tasks_created_at ON download_tasks(created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_favorites_created_at ON favorites(created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_favorites_type_created_at ON favorites(entity_type, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_collections_created_at ON collections(created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_subscriptions_created_at ON subscriptions(created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_actress_missing_summary_missing_count ON actress_missing_summary(missing_count DESC)",
        "CREATE INDEX IF NOT EXISTS idx_inventory_actors_missing_count_name ON inventory_actors(missing_count DESC, actress_name)",
        "CREATE INDEX IF NOT EXISTS idx_missing_videos_actress_id ON missing_videos(actress_id)",
        "CREATE INDEX IF NOT EXISTS idx_missing_videos_release_date ON missing_videos(release_date DESC)",
        "CREATE INDEX IF NOT EXISTS idx_missing_videos_actress_release ON missing_videos(actress_id, release_date DESC)",
        "CREATE INDEX IF NOT EXISTS idx_inventory_videos_actress_release ON inventory_videos(actress_id, release_date DESC)",
        "CREATE INDEX IF NOT EXISTS idx_emby_snapshots_snapshot_key ON emby_snapshots(snapshot_key, actress_id)",
        "CREATE INDEX IF NOT EXISTS idx_emby_snapshots_snapshot_title_item ON emby_snapshots(snapshot_key, title, emby_item_id)",
        "CREATE INDEX IF NOT EXISTS idx_emby_actors_snapshot_key ON emby_actors(snapshot_key)",
        "CREATE INDEX IF NOT EXISTS idx_emby_actors_snapshot_name ON emby_actors(snapshot_key, actress_name)",
        "CREATE INDEX IF NOT EXISTS idx_emby_actors_snapshot_total_videos ON emby_actors(snapshot_key, total_videos DESC)",
        "CREATE INDEX IF NOT EXISTS idx_emby_actors_updated_at ON emby_actors(updated_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_ignored_duplicates_emby_item_id ON ignored_duplicates(emby_item_id)",
        "CREATE INDEX IF NOT EXISTS idx_actor_aliases_alias_id ON actor_aliases(alias_id)",
        "CREATE INDEX IF NOT EXISTS idx_actor_aliases_canonical_id ON actor_aliases(canonical_id)",
        "CREATE INDEX IF NOT EXISTS idx_logs_created_at ON logs(created_at)",
        "CREATE INDEX IF NOT EXISTS idx_logs_level ON logs(level)",
        "CREATE INDEX IF NOT EXISTS idx_inventory_jobs_status ON inventory_jobs(status)",
        "CREATE INDEX IF NOT EXISTS idx_inventory_jobs_job_type ON inventory_jobs(job_type)",
        "CREATE INDEX IF NOT EXISTS idx_inventory_jobs_created_at ON inventory_jobs(created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_exempt_videos_created_at ON exempt_videos(created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_actor_mappings_emby_actor_id ON actor_mappings(emby_actor_id)",
        "CREATE INDEX IF NOT EXISTS idx_actor_mappings_emby_status ON actor_mappings(emby_actor_id, status)",
        "CREATE INDEX IF NOT EXISTS idx_actor_mappings_javinfo_actress_id ON actor_mappings(javinfo_actress_id)",
        "CREATE INDEX IF NOT EXISTS idx_actor_mappings_status ON actor_mappings(status)",
        "CREATE INDEX IF NOT EXISTS idx_actor_mappings_updated_created ON actor_mappings(updated_at DESC, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_actor_mappings_status_updated_created ON actor_mappings(status, updated_at DESC, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_download_candidates_status ON download_candidates(status)",
        "CREATE INDEX IF NOT EXISTS idx_download_candidates_actress_id ON download_candidates(actress_id)",
        "CREATE INDEX IF NOT EXISTS idx_download_candidates_content_id ON download_candidates(content_id)",
        "CREATE INDEX IF NOT EXISTS idx_download_candidates_actress_source_content ON download_candidates(actress_id, source, content_id)",
        "CREATE INDEX IF NOT EXISTS idx_download_candidates_status_actress_source ON download_candidates(status, actress_id, source)",
        "CREATE INDEX IF NOT EXISTS idx_download_candidates_status_source ON download_candidates(status, source)",
        "CREATE INDEX IF NOT EXISTS idx_download_candidates_status_source_release_created ON download_candidates(status, source, release_date DESC, created_at ASC, id ASC)",
        "CREATE INDEX IF NOT EXISTS idx_download_candidate_events_created ON download_candidate_events(created_at DESC, id DESC)",
        "CREATE INDEX IF NOT EXISTS idx_download_candidate_events_candidate_id_id ON download_candidate_events(candidate_id, id DESC)",
        "CREATE INDEX IF NOT EXISTS idx_candidate_process_runs_created_id ON candidate_process_runs(created_at DESC, id DESC)",
        "CREATE INDEX IF NOT EXISTS idx_video_variant_group_items_content_id ON video_variant_group_items(content_id)",
        "CREATE INDEX IF NOT EXISTS idx_video_variant_group_items_group_id ON video_variant_group_items(group_id)",
        "CREATE INDEX IF NOT EXISTS idx_video_variant_group_jobs_updated ON video_variant_group_jobs(updated_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_video_variant_group_jobs_created ON video_variant_group_jobs(created_at DESC, id DESC)",
        "CREATE INDEX IF NOT EXISTS idx_translation_jobs_created ON translation_jobs(created_at DESC, id DESC)",
        "CREATE INDEX IF NOT EXISTS idx_movie_resources_movie ON movie_resources(movie_id, status, is_default DESC)",
        "CREATE INDEX IF NOT EXISTS idx_movie_resources_task ON movie_resources(download_task_id)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_movie_resources_one_default ON movie_resources(movie_id, provider) WHERE is_default = 1 AND resource_type = 'video'",
    ]
    for sql_text in indexes:
        _create_index_if_possible(cursor, sql_text)
    conn.commit()
    conn.close()


def _migrate_subscriptions():
    """Keep older PostgreSQL databases compatible with current subscriptions shape."""
    conn = get_db_orig()
    cursor = conn.cursor()
    cursor.execute("ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS last_check TIMESTAMPTZ")
    cursor.execute("ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS last_found TEXT")
    cursor.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_subscriptions_actress_id ON subscriptions(actress_id)")
    conn.commit()
    conn.close()
    from database.subscription import cleanup_legacy_subscriptions
    cleanup_legacy_subscriptions()
