"""收藏与收藏夹数据库层"""
import json
from typing import List, Optional, Dict

import psycopg2

from database.base import get_db


class CollectionValidationError(ValueError):
    pass


class CollectionNameExistsError(ValueError):
    pass


class CollectionNotFoundError(ValueError):
    pass


def _normalize_collection_name(name: str) -> str:
    normalized = (name or "").strip()
    if not normalized:
        raise CollectionValidationError("Collection name must not be empty")
    return normalized


def init_favorite_db():
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS favorites (
                entity_type TEXT,
                entity_id TEXT,
                metadata_json TEXT DEFAULT '{}',
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (entity_type, entity_id)
            )
        ''')
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS collections (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL UNIQUE,
                description TEXT,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS collection_items (
                collection_id INTEGER,
                entity_type TEXT,
                entity_id TEXT,
                added_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (collection_id, entity_type, entity_id),
                FOREIGN KEY (collection_id) REFERENCES collections (id) ON DELETE CASCADE
            )
        ''')


def toggle_favorite(entity_type: str, entity_id: str, metadata: Optional[Dict] = None) -> bool:
    """切换收藏状态。返回 True 表示已收藏，False 表示已取消。"""
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT 1 FROM favorites WHERE entity_type = ? AND entity_id = ?",
            (entity_type, entity_id)
        )
        exists = cursor.fetchone()
        if exists:
            cursor.execute(
                "DELETE FROM favorites WHERE entity_type = ? AND entity_id = ?",
                (entity_type, entity_id)
            )
            return False
        else:
            cursor.execute(
                "INSERT INTO favorites (entity_type, entity_id, metadata_json) VALUES (?, ?, ?)",
                (entity_type, entity_id, json.dumps(metadata or {}))
            )
            return True


def is_favorite(entity_type: str, entity_id: str) -> bool:
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT 1 FROM favorites WHERE entity_type = ? AND entity_id = ?",
            (entity_type, entity_id)
        )
        return cursor.fetchone() is not None


def list_favorites(entity_type: Optional[str] = None) -> List[Dict]:
    with get_db() as conn:
        cursor = conn.cursor()
        if entity_type:
            cursor.execute(
                "SELECT entity_type, entity_id, metadata_json, created_at FROM favorites WHERE entity_type = ? ORDER BY created_at DESC",
                (entity_type,)
            )
        else:
            cursor.execute(
                "SELECT entity_type, entity_id, metadata_json, created_at FROM favorites ORDER BY created_at DESC"
            )
        rows = cursor.fetchall()
        result = []
        for row in rows:
            item = dict(row)
            item['metadata'] = json.loads(item.pop('metadata_json') or '{}')
            result.append(item)
        return result


def list_collections() -> List[Dict]:
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT id, name, description, created_at FROM collections ORDER BY created_at DESC")
        rows = cursor.fetchall()
        return [dict(row) for row in rows]


def get_collection(collection_id: int) -> Optional[Dict]:
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT id, name, description, created_at FROM collections WHERE id = ?",
            (collection_id,)
        )
        row = cursor.fetchone()
        return dict(row) if row else None


def create_collection(name: str, description: Optional[str] = None) -> Dict:
    normalized_name = _normalize_collection_name(name)
    try:
        with get_db() as conn:
            cursor = conn.cursor()
            cursor.execute(
                "INSERT INTO collections (name, description) VALUES (?, ?)",
                (normalized_name, description)
            )
            collection_id = cursor.lastrowid
            cursor.execute(
                "SELECT id, name, description, created_at FROM collections WHERE id = ?",
                (collection_id,)
            )
            return dict(cursor.fetchone())
    except psycopg2.IntegrityError as exc:
        raise CollectionNameExistsError("Collection name already exists") from exc
        raise


def update_collection(collection_id: int, name: str, description: Optional[str] = None) -> Dict:
    normalized_name = _normalize_collection_name(name)
    try:
        with get_db() as conn:
            cursor = conn.cursor()
            cursor.execute(
                "UPDATE collections SET name = ?, description = ? WHERE id = ?",
                (normalized_name, description, collection_id)
            )
            if cursor.rowcount == 0:
                raise CollectionNotFoundError("Collection not found")
            cursor.execute(
                "SELECT id, name, description, created_at FROM collections WHERE id = ?",
                (collection_id,)
            )
            return dict(cursor.fetchone())
    except psycopg2.IntegrityError as exc:
        raise CollectionNameExistsError("Collection name already exists") from exc


def delete_collection(collection_id: int) -> bool:
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute(
            "DELETE FROM collection_items WHERE collection_id = ?",
            (collection_id,)
        )
        cursor.execute(
            "DELETE FROM collections WHERE id = ?",
            (collection_id,)
        )
        return cursor.rowcount > 0
