"""收藏与收藏夹数据库层"""
import json
import time
from typing import List, Optional, Dict

import psycopg2

from database.base import get_db


class CollectionValidationError(ValueError):
    pass


class CollectionNameExistsError(ValueError):
    pass


class CollectionNotFoundError(ValueError):
    pass


def _bump_favorites_generation() -> None:
    try:
        from services.cache import set_data_generation

        set_data_generation("favorites", time.time_ns())
    except Exception:
        pass


def _normalize_collection_name(name: str) -> str:
    normalized = (name or "").strip()
    if not normalized:
        raise CollectionValidationError("Collection name must not be empty")
    return normalized


def init_favorite_db():
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS favorites (
                entity_type TEXT,
                entity_id TEXT,
                metadata_json TEXT DEFAULT '{}',
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (entity_type, entity_id)
            )
        ''')
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS collections (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL UNIQUE,
                description TEXT,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS collection_items (
                collection_id INTEGER,
                entity_type TEXT,
                entity_id TEXT,
                added_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (collection_id, entity_type, entity_id),
                FOREIGN KEY (collection_id) REFERENCES collections (id) ON DELETE CASCADE
            )
        ''')
    cleanup_legacy_video_favorites()


def _is_legacy_video_favorite(entity_id: str, metadata_json: str) -> bool:
    try:
        metadata = json.loads(metadata_json or "{}")
    except json.JSONDecodeError:
        metadata = {}
    service_code = str(metadata.get("service_code") or "").strip()
    if not service_code:
        return False
    return not str(entity_id or "").endswith(f"::{service_code}")


def cleanup_legacy_video_favorites() -> int:
    """删除旧版 video 收藏记录，避免与当前 service-qualified ID 重复。"""
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT entity_id, metadata_json FROM favorites WHERE entity_type = ?",
            ("video",),
        )
        legacy_ids = [
            row["entity_id"]
            for row in cursor.fetchall()
            if _is_legacy_video_favorite(row["entity_id"], row["metadata_json"])
        ]
        if not legacy_ids:
            return 0
        cursor.executemany(
            "DELETE FROM favorites WHERE entity_type = ? AND entity_id = ?",
            [("video", entity_id) for entity_id in legacy_ids],
        )
        removed = len(legacy_ids)
    _bump_favorites_generation()
    return removed


def toggle_favorite(entity_type: str, entity_id: str, metadata: Optional[Dict] = None) -> bool:
    """切换收藏状态。返回 True 表示已收藏，False 表示已取消。"""
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT 1 FROM favorites WHERE entity_type = ? AND entity_id = ?",
            (entity_type, entity_id)
        )
        exists = cursor.fetchone()
        if exists:
            cursor.execute(
                "DELETE FROM favorites WHERE entity_type = ? AND entity_id = ?",
                (entity_type, entity_id)
            )
            is_favorited = False
        else:
            cursor.execute(
                "INSERT INTO favorites (entity_type, entity_id, metadata_json) VALUES (?, ?, ?)",
                (entity_type, entity_id, json.dumps(metadata or {}))
            )
            is_favorited = True
    _bump_favorites_generation()
    return is_favorited


def set_favorite(
    entity_type: str,
    entity_id: str,
    metadata: Optional[Dict] = None,
    favorited: bool = True,
) -> bool:
    """Idempotently add/remove one favorite row. Returns True when changed.

    Used by the variant-group toggle: favoriting a video favorites EVERY
    version of the work, so the router needs explicit set semantics instead
    of per-row toggling (which would flip already-favorited siblings off).
    """
    with get_db() as conn:
        cursor = conn.cursor()
        if favorited:
            cursor.execute(
                "SELECT 1 FROM favorites WHERE entity_type = ? AND entity_id = ?",
                (entity_type, entity_id)
            )
            if cursor.fetchone():
                changed = False
            else:
                cursor.execute(
                    "INSERT INTO favorites (entity_type, entity_id, metadata_json) VALUES (?, ?, ?)",
                    (entity_type, entity_id, json.dumps(metadata or {}))
                )
                changed = True
        else:
            cursor.execute(
                "DELETE FROM favorites WHERE entity_type = ? AND entity_id = ?",
                (entity_type, entity_id)
            )
            changed = cursor.rowcount > 0
    if changed:
        _bump_favorites_generation()
    return changed


def is_favorite(entity_type: str, entity_id: str) -> bool:
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT 1 FROM favorites WHERE entity_type = ? AND entity_id = ?",
            (entity_type, entity_id)
        )
        return cursor.fetchone() is not None


def list_favorites(entity_type: Optional[str] = None) -> List[Dict]:
    with get_db() as conn:
        cursor = conn.cursor()
        if entity_type:
            cursor.execute(
                "SELECT entity_type, entity_id, metadata_json, created_at FROM favorites WHERE entity_type = ? ORDER BY created_at DESC",
                (entity_type,)
            )
        else:
            cursor.execute(
                "SELECT entity_type, entity_id, metadata_json, created_at FROM favorites ORDER BY created_at DESC"
            )
        rows = cursor.fetchall()
        result = []
        for row in rows:
            item = dict(row)
            try:
                item['metadata'] = json.loads(item.pop('metadata_json') or '{}')
            except json.JSONDecodeError:
                item['metadata'] = {}
            result.append(item)
        return result


def list_favorite_index(entity_type: Optional[str] = None) -> List[Dict]:
    """Return the lightweight favorite registry without metadata blobs."""
    with get_db() as conn:
        cursor = conn.cursor()
        if entity_type:
            cursor.execute(
                "SELECT entity_type, entity_id, created_at FROM favorites WHERE entity_type = ? ORDER BY created_at DESC",
                (entity_type,),
            )
        else:
            cursor.execute(
                "SELECT entity_type, entity_id, created_at FROM favorites ORDER BY created_at DESC"
            )
        return [dict(row) for row in cursor.fetchall()]


def _favorite_row(row, include_metadata: bool) -> Dict:
    item = dict(row)
    if include_metadata:
        try:
            item["metadata"] = json.loads(item.pop("metadata_json") or "{}")
        except json.JSONDecodeError:
            item["metadata"] = {}
    else:
        item.pop("metadata_json", None)
    return item


def list_favorites_page(
    entity_type: Optional[str] = None,
    *,
    limit: int = 50,
    offset: int = 0,
    include_metadata: bool = True,
) -> Dict:
    page_size = max(1, min(int(limit or 50), 200))
    start = max(0, int(offset or 0))
    metadata_column = ", metadata_json" if include_metadata else ""
    with get_db() as conn:
        cursor = conn.cursor()
        if entity_type:
            cursor.execute(
                "SELECT COUNT(*) AS cnt FROM favorites WHERE entity_type = ?",
                (entity_type,),
            )
            total = int(cursor.fetchone()["cnt"] or 0)
            cursor.execute(
                f"""
                SELECT entity_type, entity_id{metadata_column}, created_at
                FROM favorites
                WHERE entity_type = ?
                ORDER BY created_at DESC
                LIMIT ? OFFSET ?
                """,
                (entity_type, page_size, start),
            )
        else:
            cursor.execute("SELECT COUNT(*) AS cnt FROM favorites")
            total = int(cursor.fetchone()["cnt"] or 0)
            cursor.execute(
                f"""
                SELECT entity_type, entity_id{metadata_column}, created_at
                FROM favorites
                ORDER BY created_at DESC
                LIMIT ? OFFSET ?
                """,
                (page_size, start),
            )
        rows = cursor.fetchall()
    return {
        "data": [_favorite_row(row, include_metadata) for row in rows],
        "total": total,
        "limit": page_size,
        "offset": start,
    }


def list_collections() -> List[Dict]:
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT id, name, description, created_at FROM collections ORDER BY created_at DESC")
        rows = cursor.fetchall()
        return [dict(row) for row in rows]


def get_collection(collection_id: int) -> Optional[Dict]:
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT id, name, description, created_at FROM collections WHERE id = ?",
            (collection_id,)
        )
        row = cursor.fetchone()
        return dict(row) if row else None


def create_collection(name: str, description: Optional[str] = None) -> Dict:
    normalized_name = _normalize_collection_name(name)
    try:
        with get_db() as conn:
            cursor = conn.cursor()
            cursor.execute(
                "INSERT INTO collections (name, description) VALUES (?, ?)",
                (normalized_name, description)
            )
            collection_id = cursor.lastrowid
            cursor.execute(
                "SELECT id, name, description, created_at FROM collections WHERE id = ?",
                (collection_id,)
            )
            return dict(cursor.fetchone())
    except psycopg2.IntegrityError as exc:
        raise CollectionNameExistsError("Collection name already exists") from exc


def update_collection(collection_id: int, name: str, description: Optional[str] = None) -> Dict:
    normalized_name = _normalize_collection_name(name)
    try:
        with get_db() as conn:
            cursor = conn.cursor()
            cursor.execute(
                "UPDATE collections SET name = ?, description = ? WHERE id = ?",
                (normalized_name, description, collection_id)
            )
            if cursor.rowcount == 0:
                raise CollectionNotFoundError("Collection not found")
            cursor.execute(
                "SELECT id, name, description, created_at FROM collections WHERE id = ?",
                (collection_id,)
            )
            return dict(cursor.fetchone())
    except psycopg2.IntegrityError as exc:
        raise CollectionNameExistsError("Collection name already exists") from exc


def delete_collection(collection_id: int) -> bool:
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute(
            "DELETE FROM collection_items WHERE collection_id = ?",
            (collection_id,)
        )
        cursor.execute(
            "DELETE FROM collections WHERE id = ?",
            (collection_id,)
        )
        return cursor.rowcount > 0
