import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const vueSource = readFileSync(new URL('./SupplementManagement.vue', import.meta.url), 'utf8')
const externalStyle = readFileSync(new URL('../features/supplement/supplementManagement.css', import.meta.url), 'utf8')
const actorPicker = readFileSync(new URL('../features/supplement/ActorPickerView.vue', import.meta.url), 'utf8')
const jobList = readFileSync(new URL('../features/supplement/SupplementJobList.vue', import.meta.url), 'utf8')
const sourceHealthPanelVue = readFileSync(new URL('../features/supplement/SourceHealthPanel.vue', import.meta.url), 'utf8')
const sourceHealthStyle = readFileSync(new URL('../features/supplement/sourceHealthPanel.css', import.meta.url), 'utf8')
const sourceHealthPanel = `${sourceHealthPanelVue}\n${sourceHealthStyle}`
const moviesPanel = readFileSync(new URL('../features/supplement/SupplementMoviesPanel.vue', import.meta.url), 'utf8')
const diagnosticsDialog = readFileSync(new URL('../features/supplement/SupplementSourceDiagnosticsDialog.vue', import.meta.url), 'utf8')
const moviesStyle = [
  readFileSync(new URL('../features/supplement/supplementMoviesPanel.css', import.meta.url), 'utf8'),
  readFileSync(new URL('../features/supplement/supplementMovieRepair.css', import.meta.url), 'utf8'),
].join('\n')
const diagnosticsStyle = [
  readFileSync(new URL('../features/supplement/supplementSourceDiagnosticsDialog.css', import.meta.url), 'utf8'),
  readFileSync(new URL('../features/supplement/supplementDiagnosticsFields.css', import.meta.url), 'utf8'),
].join('\n')
const source = `${vueSource}\n${externalStyle}\n${moviesPanel}\n${moviesStyle}\n${diagnosticsDialog}\n${diagnosticsStyle}`
const supplementFeatureSource = [source, actorPicker, jobList, sourceHealthPanel].join('\n')
const app = readFileSync(new URL('../App.vue', import.meta.url), 'utf8')

function cssBlock(content, selector) {
  const blocks = [...content.matchAll(/([^{}]+)\{([^{}]*)\}/g)]
  const match = blocks.find(([, selectors]) => selectors
    .split(',')
    .map(part => part.trim())
    .includes(selector))
  assert.ok(match, `${selector} block should exist`)
  return match[2]
}

function backgroundIncludes(block, token) {
  const match = block.match(/background:\s*([^;]+);/)
  return Boolean(match && match[1].includes(token))
}

function assertLayeredBackground(block, token, name) {
  assert.ok(backgroundIncludes(block, token), `${name} should include ${token}`)
  assert.match(block, /var\(--surface-specular-edge/, `${name} should include a specular edge layer`)
  assert.match(block, /var\(--surface-noise\)/, `${name} should include the shared noise layer`)
}

test('supplement management shows and controls actor context when routed from an actor', () => {
  assert.match(source, /v-if="actorContext"/)
  assert.match(source, /class="actor-context-card"/)
  assert.match(source, /api\.getActress\(normalized\)/)
  assert.match(source, /clearActorContext\(\)/)
  assert.match(source, /goActorContext\(\)/)
  assert.match(source, /applyJobActorContext\(job\)/)
})

test('supplement management keeps heavyweight styles in an external scoped stylesheet', () => {
  assert.match(vueSource, /<style scoped src="\.\.\/features\/supplement\/supplementManagement\.css"><\/style>/)
  assert.match(moviesPanel, /<style scoped src="\.\/supplementMoviesPanel\.css"><\/style>/)
  assert.match(moviesPanel, /<style scoped src="\.\/supplementMovieRepair\.css"><\/style>/)
  assert.match(diagnosticsDialog, /<style scoped src="\.\/supplementSourceDiagnosticsDialog\.css"><\/style>/)
  assert.match(diagnosticsDialog, /<style scoped src="\.\/supplementDiagnosticsFields\.css"><\/style>/)
  assert.ok(`${externalStyle}\n${moviesStyle}\n${diagnosticsStyle}`.length > 15000, 'external supplement stylesheets should carry the moved workspace CSS')
  assert.ok(vueSource.split('\n').length < 1500, 'SupplementManagement.vue should stay small enough to review and parse quickly')
})

test('supplement management keeps jobs and movies scoped to actor context', () => {
  assert.match(source, /applyActorContext\(actressId\)/)
  assert.match(source, /this\.jobFilters\.actress_id = normalized/)
  assert.match(source, /this\.movieFilters\.actress_id = normalized/)
  assert.match(source, /jobActorLabel\(job\)/)
})

test('supplement management lets users search and select an actor instead of typing ids', () => {
  assert.match(source, /v-model:keyword="actorSearchKeyword"/)
  assert.match(source, /searchActorContext\(\)/)
  assert.match(source, /selectActorContext/)
  assert.match(source, /api\.searchActors\(keyword\)/)
  assert.match(actorPicker, /v-for="actor in actors"/)
  assert.match(source, /actorChoiceCards/)
  assert.match(actorPicker, /ActorPortraitCard/)
  assert.match(actorPicker, /density="compact"/)
  assert.match(actorPicker, /action-label="选择"/)
  assert.doesNotMatch(actorPicker, /class="actor-choice-card apple-surface"/)
  assert.doesNotMatch(actorPicker, /class="select-orb"/)
  assert.doesNotMatch(supplementFeatureSource, /placeholder="演员 ID"/)
})

test('supplement management defaults to an actor-first selection view', () => {
  assert.match(source, /补全演员/)
  assert.match(source, /v-if="showActorPicker"/)
  assert.match(actorPicker, /class="actor-search-panel apple-surface"/)
  assert.match(actorPicker, /class="actor-choice-grid"/)
  assert.match(source, /recentActorJobs/)
})

test('supplement management builds recent actor cards without fanout actor detail requests', () => {
  const loadRecentActorJobsBlock = source.match(/async loadRecentActorJobs\(\{ silent = false \} = \{\}\) \{[\s\S]*?\n    \},/)?.[0] || ''

  assert.match(loadRecentActorJobsBlock, /api\.listSupplementJobs\(\{ page: 1, page_size: 16 \}\)/)
  assert.match(loadRecentActorJobsBlock, /this\.recentActors = this\.recentActorJobs\.map\(this\.recentActorFromJob\)/)
  assert.match(source, /recentActorFromJob\(job\)/)
  assert.doesNotMatch(loadRecentActorJobsBlock, /loadRecentActors|api\.getActress/)
  assert.doesNotMatch(source, /api\.getActress\(job\.local_actress_id\)/)
})

test('supplement management uses an actor workspace with segmented panels', () => {
  assert.match(source, /class="actor-workspace-hero apple-surface"/)
  assert.match(source, /workspaceSegments/)
  assert.match(source, /activeWorkspaceSegment/)
  assert.match(source, /const SupplementMoviesPanel = defineAsyncComponent/)
  assert.match(source, /const SupplementSourceDiagnosticsDialog = defineAsyncComponent/)
  assert.match(source, /作品字段/)
  assert.match(source, /任务队列/)
  assert.match(source, /来源诊断/)
  assert.match(sourceHealthPanel, /来源状态/)
  assert.match(jobList, /jobAttemptMeta/)
  assert.match(jobList, /next_run_at/)
  assert.match(source, /getSupplementActressStatus\(normalized\)/)
  assert.match(source, /startSupplementFilmographyJob\(this\.actorContext\.id\)/)
  assert.match(source, /refreshSupplementActressResolved\(this\.actorContext\.id\)/)
  assert.match(source, /生成下载候选/)
  assert.match(source, /createDownloadCandidates/)
  assert.match(source, /api\.createSupplementDownloadCandidates\(params\)/)
  assert.match(source, /path: '\/downloads'/)
  assert.match(source, /source: 'supplement'/)
})

test('supplement workspace segments expose repair counts and status hints', () => {
  assert.match(vueSource, /workspaceSegmentMeta\(segment\.key\)/)
  assert.match(vueSource, /workspaceSegmentClass\(segment\.key\)/)
  assert.match(vueSource, /class="segment-label"/)
  assert.match(vueSource, /class="segment-count"/)
  assert.match(vueSource, /class="segment-status"/)
  assert.match(vueSource, /class="segment-next-step"/)
  assert.match(vueSource, /workspaceSegmentMeta\(segment\.key\)\.nextStep/)
  assert.match(source, /workspaceSegmentMeta\(key\)/)
  assert.match(source, /workspaceSegmentClass\(key\)/)
  assert.match(source, /jobsTotalCount/)
  assert.match(source, /moviesTotalCount/)
  assert.match(source, /sourceHealthRows\.length/)
  assert.match(source, /sourceDiagnosticsOpen \? '检查中' : '待选择'/)
  assert.match(source, /任务进行中/)
  assert.match(source, /lastJobStatus/)
  assert.match(source, /任务失败/)
  assert.match(source, /workspaceJobStatusCounts\(\)/)
  assert.match(source, /const failedJobs = this\.workspaceJobStatusCounts\.failed/)
  assert.match(source, /if \(failedJobs > 0 \|\| lastJobStatus === 'failed'\)/)
  assert.match(source, /const runningJobs = this\.workspaceJobStatusCounts\.running \+ this\.workspaceJobStatusCounts\.queued/)
  assert.match(source, /nextStep: '先补字段'/)
  assert.match(source, /nextStep: '处理失败任务'/)
  assert.match(source, /nextStep: '打开诊断'/)
  assert.match(source, /nextStep: '查看降级来源'/)
  assert.match(source, /\['degraded', 'cooling_down', 'paused'\]\.includes\(source\.runtime_status\)/)
  assert.doesNotMatch(source, /source => !\['healthy', 'ok'\]\.includes\(source\.status\)/)
  assert.match(source, /tone: 'failed'/)
  assert.match(source, /tone: 'warning'/)
  assert.match(source, /tone: 'ready'/)
  assert.match(externalStyle, /\.segment-next-step/)
  assert.match(externalStyle, /\.segmented-control button\.segment-failed/)
  assert.match(externalStyle, /\.segmented-control button\.segment-warning/)
  assert.match(externalStyle, /\.segmented-control button\.segment-ready/)
})

test('supplement actor workspace labels supplement and variant counts clearly', () => {
  assert.match(vueSource, />刷新版本条目<\/button>/)
  assert.match(vueSource, />补全来源<\/p>/)
  assert.match(vueSource, />已匹配片库<\/p>/)
  assert.match(vueSource, />补全新增<\/p>/)
  assert.match(vueSource, />含版本条目<\/p>/)
  assert.match(vueSource, /已刷新版本条目/)
  assert.doesNotMatch(vueSource, />刷新可展示<\/button>/)
  assert.doesNotMatch(vueSource, />补全影片<\/p>/)
  assert.doesNotMatch(vueSource, />已匹配<\/p>/)
  assert.doesNotMatch(vueSource, />仅补全<\/p>/)
  assert.doesNotMatch(vueSource, />可展示<\/p>/)
  assert.doesNotMatch(vueSource, /已刷新可展示影片/)
})

test('supplement actor workspace summarizes repair queue state', () => {
  assert.match(vueSource, /class="workspace-command-strip"/)
  assert.match(vueSource, /class="command-strip-primary"/)
  assert.match(vueSource, /class="workspace-repair-actions"/)
  assert.match(vueSource, /v-for="action in workspaceRepairActions"/)
  assert.match(vueSource, /workspaceRepairActionClass\(action\)/)
  assert.match(vueSource, /@click="runWorkspaceRepairAction\(action\)"/)
  assert.match(vueSource, /class="repair-action-value"/)
  assert.match(vueSource, /class="repair-action-label"/)
  assert.match(vueSource, /class="repair-action-hint"/)
  assert.match(vueSource, /class="task-state-track"/)
  assert.match(vueSource, /class="task-state-dot"/)
  assert.match(vueSource, /class="task-state-detail-grid"/)
  assert.match(vueSource, /workspaceTaskDetails/)
  assert.match(vueSource, /workspaceRepairActions/)
  assert.match(vueSource, /下一步动作/)
  assert.match(vueSource, /isSupplementFailed/)
  assert.match(vueSource, /{{ workspaceRepairSummary }}/)
  assert.match(source, /workspaceRepairSummary\(\)/)
  assert.match(source, /workspaceRepairTone\(\)/)
  assert.match(source, /workspaceTaskDetails\(\)/)
  assert.match(source, /workspaceRepairActions\(\)/)
  assert.match(source, /workspaceRepairActionClass\(action\)/)
  assert.match(source, /runWorkspaceRepairAction\(action\)/)
  assert.match(source, /workspaceMovieFieldGapCount\(\)/)
  assert.match(source, /workspacePendingCandidateCount\(\)/)
  assert.match(source, /workspaceDetailTargetCount\(\)/)
  assert.match(source, /this\.supplementMovies\.filter\(movie => this\.movieMatchClass\(movie\) === 'candidate'\)\.length/)
  assert.match(source, /this\.supplementMovies\.reduce\(\(total, movie\)/)
  assert.match(source, /last_job/)
  assert.match(source, /attempt_count/)
  assert.match(source, /last_error/)
  assert.match(source, /next_run_at/)
  assert.match(source, /失败原因/)
  assert.match(source, /尝试次数/)
  assert.match(source, /查看来源状态/)
  assert.match(source, /查看任务队列/)
  assert.match(source, /修复作品字段/)
  assert.match(source, /打开来源诊断/)
  assert.match(source, /失败来源/)
  assert.match(source, /候选确认/)
  assert.match(source, /字段缺口/)
  assert.match(source, /诊断入口/)
  assert.match(source, /action\.target === 'sourceHealth'/)
  assert.match(source, /action\.target === 'jobs'/)
  assert.match(source, /action\.target === 'movies'/)
  assert.match(source, /action\.target === 'diagnostics'/)
  assert.match(source, /return 'failed'/)
  assert.match(source, /return '任务失败待处理'/)
  assert.match(source, /return '需要补字段'/)
  assert.match(source, /return '等待匹配确认'/)
  assert.match(source, /return '任务进行中'/)
  assert.match(source, /return '字段完整度稳定'/)
  assert.match(externalStyle, /\.workspace-command-strip/)
  assert.match(externalStyle, /\.workspace-repair-actions/)
  assert.match(externalStyle, /\.workspace-repair-action/)
  assert.match(externalStyle, /\.workspace-repair-action\.primary/)
  assert.match(externalStyle, /\.workspace-repair-action\.failed/)
  assert.match(externalStyle, /\.workspace-repair-action\.ready/)
  assert.match(externalStyle, /\.repair-action-value/)
  assert.match(externalStyle, /\.repair-action-label/)
  assert.match(externalStyle, /\.repair-action-hint/)
  assert.match(externalStyle, /\.task-state-track/)
  assert.match(externalStyle, /\.task-state-detail-grid/)
  assert.match(externalStyle, /\.task-state-detail/)
  assert.match(externalStyle, /\.task-state-dot\.failed/)

  const commandStrip = cssBlock(externalStyle, '.workspace-command-strip')
  const repairActions = cssBlock(externalStyle, '.workspace-repair-actions')
  const repairAction = cssBlock(externalStyle, '.workspace-repair-action')
  const repairActionHint = cssBlock(externalStyle, '.repair-action-hint')
  assert.match(commandStrip, /grid-template-columns:\s*minmax\(220px,\s*0\.9fr\)\s*minmax\(220px,\s*1fr\)\s*minmax\(0,\s*1fr\)/)
  assert.match(commandStrip, /min-width:\s*0/)
  assert.match(commandStrip, /overflow:\s*hidden/)
  assert.match(repairActions, /grid-template-columns:\s*repeat\(4,\s*minmax\(66px,\s*1fr\)\)/)
  assert.match(repairActions, /gap:\s*6px/)
  assert.match(repairActions, /width:\s*100%/)
  assert.match(repairAction, /max-width:\s*100%/)
  assert.match(repairActionHint, /white-space:\s*normal/)
  assert.match(repairActionHint, /overflow-wrap:\s*anywhere/)
  assert.match(repairActionHint, /-webkit-line-clamp:\s*2/)
})

test('supplement diagnostics segment exposes a repair launchpad before a movie is opened', () => {
  assert.match(vueSource, /class="diagnostics-launchpad"/)
  assert.match(vueSource, /class="diagnostics-launchpad-grid"/)
  assert.match(vueSource, /v-for="row in diagnosticsLaunchpadRows"/)
  assert.match(vueSource, /class="diagnostics-launchpad-card"/)
  assert.match(vueSource, /class="diagnostics-focus-movie"/)
  assert.match(vueSource, /diagnosticsFocusMovie/)
  assert.match(vueSource, /diagnosticsFocusMovieBadges/)
  assert.match(vueSource, /openDiagnosticsFocusMovie/)
  assert.match(vueSource, /@click="setWorkspaceSegment\('movies'\)"/)
  assert.match(vueSource, /@click="openDiagnosticsFocusMovie"/)
  assert.match(source, /diagnosticsLaunchpadRows\(\)/)
  assert.match(source, /diagnosticsFocusMovie\(\)/)
  assert.match(source, /diagnosticsFocusMovieBadges\(\)/)
  assert.match(source, /openDiagnosticsFocusMovie\(\)/)
  assert.match(source, /if \(segment === 'diagnostics'\) await this\.loadMovies\(\{ silent: true, \.\.\.options \}\)/)
  assert.match(source, /workspacePendingCandidateCount/)
  assert.match(source, /workspaceMovieFieldGapCount/)
  assert.match(source, /workspaceDetailTargetCount/)
  assert.match(source, /待确认候选/)
  assert.match(source, /字段缺口/)
  assert.match(source, /可补详情/)
  assert.match(source, /打开首个待诊断影片/)
  assert.match(source, /this\.supplementMovies\.find\(movie => this\.movieMatchClass\(movie\) === 'candidate'\)/)
  assert.match(source, /this\.openMovieSources\(this\.diagnosticsFocusMovie\)/)
  assert.match(externalStyle, /\.diagnostics-launchpad/)
  assert.match(externalStyle, /\.diagnostics-launchpad-grid/)
  assert.match(externalStyle, /\.diagnostics-launchpad-card/)
  assert.match(externalStyle, /\.diagnostics-focus-movie/)
  assert.match(externalStyle, /\.diagnostics-focus-badges/)
  assert.match(externalStyle, /\.diagnostics-focus-actions/)
})

test('supplement workspace segmented controls use shared Apple glass materials', () => {
  const segmented = cssBlock(source, '.segmented-control')
  assertLayeredBackground(segmented, '--material-glass-control', 'supplement segmented control')
  assert.match(segmented, /border:\s*1px solid var\(--glass-control-border\)/)
  assert.match(segmented, /box-shadow:\s*var\(--glass-control-shadow\)/)
  assert.match(segmented, /backdrop-filter:\s*blur\(var\(--glass-blur-control\)\)\s*saturate\(var\(--glass-saturate-control\)\)/)

  const segmentButton = cssBlock(source, '.segmented-control button')
  assertLayeredBackground(segmentButton, '--material-glass-subtle', 'supplement segmented button')
  assert.match(segmentButton, /border:\s*1px solid transparent/)
  assert.match(segmentButton, /transition:\s*transform var\(--motion-standard\),\s*opacity var\(--motion-fast\)/)
  assert.doesNotMatch(segmentButton, /transition:[^;]*(?:background|border-color|box-shadow|color|filter|backdrop-filter)/)
  assert.doesNotMatch(segmentButton, /background:\s*transparent|border:\s*0|transition:\s*all/)

  const hoverButton = cssBlock(source, '.segmented-control button:hover')
  assertLayeredBackground(hoverButton, '--material-glass-control-hover', 'supplement segmented hovered button')
  assert.match(hoverButton, /border-color:\s*var\(--glass-control-border-hover\)/)

  const activeButton = cssBlock(source, '.segmented-control button.active')
  assertLayeredBackground(activeButton, '--glass-active-material', 'supplement segmented active button')
  assert.match(activeButton, /border-color:\s*var\(--glass-active-border\)/)
  assert.match(activeButton, /box-shadow:\s*var\(--glass-active-shadow\)/)
  assert.doesNotMatch(activeButton, /inset 0 -2px 0/)
  assert.doesNotMatch([segmented, segmentButton, hoverButton, activeButton].join('\n'), /^.*background:\s*var\(--(?:material-glass-control|material-glass-subtle|material-glass-control-hover|glass-active-material)\);.*$/gm)
})

test('supplement movie panel presents dense field repair cards', () => {
  assert.match(moviesPanel, /class="movies-panel-toolbar"/)
  assert.match(moviesPanel, /class="movie-field-ledger"/)
  assert.match(moviesPanel, /class="movie-field-priority-strip"/)
  assert.match(moviesPanel, /class="movie-repair-queue"/)
  assert.match(moviesPanel, /class="movie-repair-flow"/)
  assert.match(moviesPanel, /class="movie-field-triage-board"/)
  assert.match(moviesPanel, /aria-label="字段分拣台"/)
  assert.match(moviesPanel, /class="field-triage-summary"/)
  assert.match(moviesPanel, /class="field-triage-grid"/)
  assert.match(moviesPanel, /class="field-triage-card"/)
  assert.match(moviesPanel, /v-for="lane in movieFieldTriageLanes"/)
  assert.match(moviesPanel, /fieldTriageLaneClass\(lane\)/)
  assert.match(moviesPanel, /class="repair-flow-step"/)
  assert.match(moviesPanel, /movieFieldSummaryRows/)
  assert.match(moviesPanel, /movieFieldSummaryTotalMissing/)
  assert.match(moviesPanel, /movieFieldPriorityRows/)
  assert.match(moviesPanel, /movieFieldTriageLanes/)
  assert.match(moviesPanel, /movieFieldTriageTotal/)
  assert.match(moviesPanel, /movieFieldTriageSamples/)
  assert.match(moviesPanel, /fieldPriorityClass\(row\)/)
  assert.match(moviesPanel, /movieRepairQueueRows/)
  assert.match(moviesPanel, /movieRepairQueueTotal/)
  assert.match(moviesPanel, /movieRepairFlowSteps/)
  assert.match(moviesPanel, /当前页字段缺口/)
  assert.match(moviesPanel, /字段优先级/)
  assert.match(moviesPanel, /字段分拣/)
  assert.match(moviesPanel, /可补详情/)
  assert.match(moviesPanel, /需诊断/)
  assert.match(moviesPanel, /等待来源/)
  assert.match(moviesPanel, /字段已齐/)
  assert.match(moviesPanel, /打开详情补抓/)
  assert.match(moviesPanel, /先确认来源/)
  assert.match(moviesPanel, /等待匹配/)
  assert.match(moviesPanel, /可生成候选/)
  assert.match(moviesPanel, /优先补详情/)
  assert.match(moviesPanel, /打开诊断确认来源/)
  assert.match(moviesPanel, /当前页修复队列/)
  assert.match(moviesPanel, /当前页处理线/)
  assert.match(moviesPanel, /待确认/)
  assert.match(moviesPanel, /需补详情/)
  assert.match(moviesPanel, /字段已齐/)
  assert.match(moviesPanel, /先确认候选/)
  assert.match(moviesPanel, /批量补字段/)
  assert.match(moviesPanel, /生成候选包/)
  assert.match(moviesPanel, /个缺口/)
  assert.match(moviesPanel, /class="movie-field-grid"/)
  assert.match(moviesPanel, /class="field-chip"/)
  assert.match(moviesPanel, /missing: !chip\.value/)
  assert.match(moviesPanel, /class="movie-field-repair-summary"/)
  assert.match(moviesPanel, /class="field-repair-priority"/)
  assert.match(moviesPanel, /class="field-repair-status"/)
  assert.match(moviesPanel, /class="movie-field-work-orders"/)
  assert.match(moviesPanel, /v-for="order in movieFieldWorkOrders\(movie\)"/)
  assert.match(moviesPanel, /class="field-work-order-chip"/)
  assert.match(moviesPanel, /movieFieldRepairSummary\(movie\)/)
  assert.match(moviesPanel, /fieldRepairSummaryClass\(summary\)/)
  assert.match(moviesPanel, /movieFieldWorkOrders\(movie\)/)
  assert.match(moviesPanel, /fieldWorkOrderClass\(order\)/)
  assert.match(moviesPanel, /fieldWorkOrderAction\(chip, movie\)/)
  assert.match(moviesPanel, /class="movie-repair-flags"/)
  assert.match(moviesPanel, /class="movie-repair-stage-grid"/)
  assert.match(moviesPanel, /movieRepairStages\(movie\)/)
  assert.match(moviesPanel, /repairStageClass\(stage\)/)
  assert.match(moviesPanel, /movieFieldChips\(movie\)/)
  assert.match(moviesPanel, /movieMissingFieldChips\(movie\)/)
  assert.match(moviesPanel, /movieRepairFlags\(movie\)/)
  assert.match(moviesPanel, /movieNeedsDetail\(movie\)/)
  assert.match(moviesPanel, /movieIsFieldComplete\(movie\)/)
  assert.match(moviesPanel, /repairQueueCardClass\(row\)/)
  assert.match(moviesPanel, /fieldChipClass\(chip\)/)
  assert.match(moviesPanel, /movieFieldSummaryRows\(\)[\s\S]*this\.supplementMovies\.forEach/)
  assert.match(moviesPanel, /movieFieldSummaryTotalMissing\(\)[\s\S]*reduce/)
  assert.match(moviesPanel, /movieFieldTriageLanes\(\)[\s\S]*const lanes = \[/)
  assert.match(moviesPanel, /movieFieldTriageLanes\(\)[\s\S]*this\.movieFieldTriageSamples\(lane\.key\)/)
  assert.match(moviesPanel, /movieFieldTriageTotal\(\)[\s\S]*reduce/)
  assert.match(moviesPanel, /movieFieldTriageSamples\(laneKey\)[\s\S]*this\.supplementMovies/)
  assert.match(moviesPanel, /movieFieldTriageSamples\(laneKey\)[\s\S]*slice\(0, 2\)/)
  assert.match(moviesPanel, /fieldTriageLaneClass\(lane\)/)
  assert.match(moviesPanel, /movieFieldPriorityRows\(\)[\s\S]*this\.movieFieldSummaryRows/)
  assert.match(moviesPanel, /movieFieldPriorityRows\(\)[\s\S]*sort\(\(a, b\) => b\.missing - a\.missing\)/)
  assert.match(moviesPanel, /movieFieldPriorityRows\(\)[\s\S]*slice\(0, 3\)/)
  assert.match(moviesPanel, /movieRepairQueueRows\(\)[\s\S]*this\.supplementMovies\.filter/)
  assert.match(moviesPanel, /movieRepairQueueTotal\(\)[\s\S]*reduce/)
  assert.match(moviesPanel, /movieRepairFlowSteps\(\)[\s\S]*this\.movieRepairQueueRows/)
  assert.match(moviesPanel, /flowStepClass\(step\)/)
  assert.match(moviesPanel, /字段完整/)
  assert.match(moviesPanel, /优先修复/)
  assert.match(moviesPanel, /详情源可用/)
  assert.match(moviesPanel, /等待详情源/)
  assert.match(moviesPanel, /字段齐全/)
  assert.match(moviesPanel, /字段修复工单/)
  assert.match(moviesPanel, /补详情可修/)
  assert.match(moviesPanel, /打开诊断/)
  assert.match(moviesPanel, /等待来源/)
  assert.match(moviesPanel, /确认匹配/)
  assert.match(moviesPanel, /补详情/)
  assert.match(moviesPanel, /生成候选/)
  assert.match(moviesPanel, /待确认/)
  assert.match(moviesPanel, /可补字段/)
  assert.match(moviesPanel, /可生成/)
  assert.match(moviesPanel, /待补齐/)
  assert.match(moviesPanel, /缺封面/)
  assert.match(moviesPanel, /缺厂牌/)
  assert.match(moviesPanel, /缺系列/)
  assert.match(moviesPanel, /movieRepairStages\(movie\)[\s\S]*this\.movieMatchClass\(movie\)/)
  assert.match(moviesPanel, /movieRepairStages\(movie\)[\s\S]*this\.movieNeedsDetail\(movie\)/)
  assert.match(moviesPanel, /movieRepairStages\(movie\)[\s\S]*this\.movieIsFieldComplete\(movie\)/)
  assert.match(moviesPanel, /movieFieldRepairSummary\(movie\)[\s\S]*const missing = this\.movieMissingFieldChips\(movie\)/)
  assert.match(moviesPanel, /movieFieldRepairSummary\(movie\)[\s\S]*primary: missing\.slice\(0, 3\)\.map\(chip => chip\.missingLabel\)\.join\(' · '\)/)
  assert.match(moviesPanel, /movieFieldRepairSummary\(movie\)[\s\S]*sourceReady: Boolean\(movie\.source_movie_id\)/)
  assert.match(moviesPanel, /movieFieldWorkOrders\(movie\)[\s\S]*this\.movieMissingFieldChips\(movie\)\.map/)
  assert.match(moviesPanel, /movieFieldChips\(movie\)[\s\S]*movieRepairFlags\(movie\)[\s\S]*this\.movieFieldChips\(movie\)\.filter/)
  assert.match(moviesStyle, /\.movie-field-ledger/)
  assert.match(moviesStyle, /\.movie-field-priority-strip/)
  assert.match(moviesStyle, /\.movie-field-triage-board/)
  assert.match(moviesStyle, /\.field-triage-summary/)
  assert.match(moviesStyle, /\.field-triage-grid/)
  assert.match(moviesStyle, /\.field-triage-card/)
  assert.match(moviesStyle, /\.field-triage-card\.ready/)
  assert.match(moviesStyle, /\.field-triage-card\.diagnose/)
  assert.match(moviesStyle, /\.field-triage-card\.waiting/)
  assert.match(moviesStyle, /\.field-triage-card\.complete/)
  assert.match(moviesStyle, /\.field-priority-chip/)
  assert.match(moviesStyle, /\.field-priority-chip\.ready/)
  assert.match(moviesStyle, /\.field-priority-chip\.clear/)
  assert.match(moviesStyle, /\.movie-repair-queue/)
  assert.match(moviesStyle, /\.movie-repair-flow/)
  assert.match(moviesStyle, /\.repair-flow-step/)
  assert.match(moviesStyle, /\.repair-flow-step\.ready/)
  assert.match(moviesStyle, /\.repair-flow-step\.empty/)
  assert.match(moviesStyle, /\.repair-queue-card/)
  assert.match(moviesStyle, /\.repair-queue-card\.ready/)
  assert.match(moviesStyle, /\.ledger-chip/)
  assert.match(moviesStyle, /\.movie-field-grid/)
  assert.match(moviesStyle, /\.field-chip\.missing/)
  assert.match(moviesStyle, /\.movie-field-repair-summary/)
  assert.match(moviesStyle, /\.movie-field-repair-summary\.ready/)
  assert.match(moviesStyle, /\.movie-field-repair-summary\.complete/)
  assert.match(moviesStyle, /\.field-repair-priority/)
  assert.match(moviesStyle, /\.field-repair-status/)
  assert.match(moviesStyle, /\.movie-field-work-orders/)
  assert.match(moviesStyle, /\.field-work-order-chip/)
  assert.match(moviesStyle, /\.field-work-order-chip\.ready/)
  assert.match(moviesStyle, /\.field-work-order-chip\.missing/)
  assert.match(moviesStyle, /\.movie-repair-stage-grid/)
  assert.match(moviesStyle, /\.repair-stage-chip/)
  assert.match(moviesStyle, /\.repair-stage-chip\.current/)
  assert.match(moviesStyle, /\.repair-stage-chip\.ready/)
  assert.match(moviesStyle, /\.repair-stage-chip\.missing/)
  assert.match(moviesStyle, /\.movie-repair-flags/)

  const triageBoard = cssBlock(moviesStyle, '.movie-field-triage-board')
  const triageGrid = cssBlock(moviesStyle, '.field-triage-grid')
  const triageCard = cssBlock(moviesStyle, '.field-triage-card')

  assertLayeredBackground(triageBoard, '--material-glass-sheet', 'movie field triage board')
  assert.match(triageBoard, /grid-template-columns:\s*minmax\(128px,\s*0\.24fr\)\s*minmax\(0,\s*1fr\)/)
  assert.match(triageGrid, /grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\)/)
  assertLayeredBackground(triageCard, '--material-glass-control', 'movie field triage card')
  assert.match(triageCard, /min-width:\s*0/)
  assert.match(triageCard, /overflow-wrap:\s*anywhere/)
})

test('supplement management exposes source health and manual correction controls', () => {
  assert.match(source, /api\.listSupplementSourcesHealth\(\)/)
  assert.match(source, /api\.listSupplementSourcesBudgets\(\)/)
  assert.match(source, /sourceHealthRows/)
  assert.match(sourceHealthPanel, /当前预算/)
  assert.match(source, /api\.pauseSupplementSource/)
  assert.match(source, /api\.resumeSupplementSource/)
  assert.match(source, /已暂停/)
  assert.match(source, /manual-match-bar/)
  assert.match(source, /manualMatchMovie/)
  assert.match(source, /api\.matchSupplementMovie/)
  assert.match(source, /api\.ignoreSupplementMovie/)
  assert.match(source, /api\.unmatchSupplementMovie/)
  assert.match(source, /manual_actions/)
  assert.match(source, /人工校正记录/)
})

test('supplement management exposes global gfriends avatar sync controls', () => {
  assert.match(source, /openSourceHealth\(\)/)
  assert.match(source, /showSourceHealthGlobal/)
  assert.match(source, /requestConfirm/)
  assert.match(source, /syncGfriendsAvatars/)
  assert.match(source, /api\.startGfriendsAvatarSyncJob\(\)/)
  assert.match(source, /loadGfriendsAvatarJob/)
  assert.match(source, /_startGfriendsAvatarPolling/)
  assert.match(source, /source: 'gfriends'/)
  assert.match(sourceHealthPanel, /头像覆盖作业/)
  assert.match(sourceHealthPanel, /同步演员头像/)
  assert.match(sourceHealthPanel, /查看头像任务/)
  assert.match(sourceHealthPanel, /匹配头像/)
  assert.match(sourceHealthPanel, /写入覆盖/)
  assert.match(sourceHealthPanel, /已校验/)
  assert.match(sourceHealthPanel, /有效头像/)
  assert.match(sourceHealthPanel, /拉取 gfriends Filetree/)
  assert.match(sourceHealthPanel, /校验图片健康/)
})

test('supplement job list names gfriends avatar sync jobs explicitly', () => {
  assert.match(jobList, /actress_avatar_sync/)
  assert.match(jobList, /gfriends 头像同步/)
})

test('supplement job list exposes dense repair status lanes', () => {
  assert.match(jobList, /class="job-repair-lane"/)
  assert.match(jobList, /v-for="item in jobRepairLaneItems\(job\)"/)
  assert.match(jobList, /class="job-repair-lane-item"/)
  assert.match(jobList, /supplementJobFailureDiagnostics/)
  assert.match(jobList, /jobFailureSummary\(job\)/)
  assert.match(jobList, /:title="job\.last_error"/)
  assert.doesNotMatch(jobList, /\{\{\s*job\.last_error\s*\}\}/)
  assert.match(jobList, /jobRepairLaneItems\(job\)/)
  assert.match(jobList, /jobRepairLaneItemClass\(item\)/)
  assert.match(jobList, /jobNextActionLabel\(job\)/)
  assert.match(jobList, /jobErrorSummary\(job\)/)
  assert.match(jobList, /任务状态/)
  assert.match(jobList, /尝试次数/)
  assert.match(jobList, /错误摘要/)
  assert.match(jobList, /下一步/)
  assert.match(jobList, /查看来源/)
  assert.match(jobList, /等待执行/)

  assert.match(jobList, /\.job-repair-lane/)
  assert.match(jobList, /\.job-repair-lane-item/)
  assert.match(jobList, /\.job-repair-lane-item\.danger/)
  assert.match(jobList, /\.job-repair-lane-item\.warning/)
  assert.match(jobList, /\.job-repair-lane-item\.ready/)
})

test('supplement job list summarizes the current task queue before row scanning', () => {
  assert.match(jobList, /class="job-queue-ledger"/)
  assert.match(jobList, /aria-label="当前任务状态概览"/)
  assert.match(jobList, /class="job-queue-summary"/)
  assert.match(jobList, /class="job-queue-cards"/)
  assert.match(jobList, /v-for="row in jobQueueSummaryRows"/)
  assert.match(jobList, /class="job-queue-card"/)
  assert.match(vueSource, /:total-count="jobsTotalCount"/)
  assert.match(jobList, /jobQueueSummaryTotal/)
  assert.match(jobList, /jobQueueTotalLabel/)
  assert.match(jobList, /jobQueueSummaryRows/)
  assert.match(jobList, /jobQueueSummaryClass\(row\)/)
  assert.match(jobList, /totalCount/)
  assert.match(jobList, /当前页任务/)
  assert.match(jobList, /筛选总量/)
  assert.match(jobList, /return `筛选总量 \$\{total\}`/)
  assert.doesNotMatch(jobList, /当前筛选任务/)
  assert.match(jobList, /失败任务/)
  assert.match(jobList, /运行中/)
  assert.match(jobList, /等待执行/)
  assert.match(jobList, /已完成/)
  assert.match(jobList, /优先重试/)
  assert.match(jobList, /观察运行/)
  assert.match(jobList, /等待调度/)
  assert.match(jobList, /归档完成/)
  assert.match(jobList, /\.job-queue-ledger/)
  assert.match(jobList, /\.job-queue-summary/)
  assert.match(jobList, /\.job-queue-total-label/)
  assert.match(jobList, /\.job-queue-cards/)
  assert.match(jobList, /\.job-queue-card/)
  assert.match(jobList, /\.job-queue-card\.danger/)
  assert.match(jobList, /\.job-queue-card\.warning/)
  assert.match(jobList, /\.job-queue-card\.ready/)

  const queueLedger = cssBlock(jobList, '.job-queue-ledger')
  const queueCards = cssBlock(jobList, '.job-queue-cards')
  const queueCard = cssBlock(jobList, '.job-queue-card')
  assert.match(queueLedger, /grid-template-columns:\s*minmax\(128px,\s*0\.28fr\)\s*minmax\(0,\s*1fr\)/)
  assert.match(queueLedger, /min-width:\s*0/)
  assert.match(queueCards, /grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(queueCard, /min-width:\s*0/)
})

test('supplement embedded panels use shared state components with next actions', () => {
  for (const [name, panel] of [
    ['SupplementMoviesPanel', moviesPanel],
    ['SupplementJobList', jobList],
    ['ActorPickerView', actorPicker],
    ['SourceHealthPanel', sourceHealthPanel],
  ]) {
    assert.doesNotMatch(panel, /<div[^>]+class="loading-wrap"[\s\S]{0,120}<div class="spinner-large"><\/div>/, `${name} should not show an isolated spinner`)
    assert.doesNotMatch(panel, />加载中\.\.\.</, `${name} should use skeleton copy instead of bare loading text`)
    assert.doesNotMatch(panel, /class="(?:empty-inline|empty-panel)[^"]*"[^>]*>暂无[^<]*<\/(?:div|small)>/, `${name} should not leave a one-line empty state`)
  }

  assert.match(moviesPanel, /import AppleSkeleton from '\.\.\/\.\.\/components\/AppleSkeleton\.vue'/)
  assert.match(moviesPanel, /import AppleEmptyState from '\.\.\/\.\.\/components\/AppleEmptyState\.vue'/)
  assert.match(moviesPanel, /<AppleSkeleton[\s\S]*label="补全影片加载中"/)
  assert.match(moviesPanel, /<AppleEmptyState[\s\S]*title="暂无补全影片"[\s\S]*next-step=/)
  assert.match(moviesPanel, /action-label="刷新影片"/)
  assert.match(moviesPanel, /secondary-action-label="清除筛选"/)
  assert.match(moviesPanel, /@action="\$emit\('refresh'\)"/)
  assert.match(moviesPanel, /@secondary-action="\$emit\('clear-filters'\)"/)

  assert.match(jobList, /import AppleSkeleton from '\.\.\/\.\.\/components\/AppleSkeleton\.vue'/)
  assert.match(jobList, /import AppleEmptyState from '\.\.\/\.\.\/components\/AppleEmptyState\.vue'/)
  assert.match(jobList, /<AppleSkeleton[\s\S]*label="补全任务加载中"/)
  assert.match(jobList, /<AppleEmptyState[\s\S]*title="暂无补全任务"[\s\S]*next-step=/)
  assert.match(jobList, /action-label="刷新任务"/)
  assert.match(jobList, /secondary-action-label="补全作品"/)
  assert.match(jobList, /@action="\$emit\('refresh'\)"/)
  assert.match(jobList, /@secondary-action="\$emit\('start-supplement'\)"/)

  assert.match(actorPicker, /import AppleEmptyState from '\.\.\/\.\.\/components\/AppleEmptyState\.vue'/)
  assert.match(actorPicker, /<AppleEmptyState[\s\S]*:title="actorEmptyState\.title"[\s\S]*:next-step="actorEmptyState\.nextStep"/)
  assert.match(actorPicker, /:action-label="actorEmptyState\.actionLabel"/)
  assert.match(actorPicker, /:secondary-action-label="actorEmptyState\.secondaryActionLabel"/)
  assert.match(actorPicker, /@action="handleEmptyAction"/)
  assert.match(actorPicker, /@secondary-action="handleEmptySecondaryAction"/)

  assert.match(sourceHealthPanel, /import AppleSkeleton from '\.\.\/\.\.\/components\/AppleSkeleton\.vue'/)
  assert.match(sourceHealthPanel, /import AppleEmptyState from '\.\.\/\.\.\/components\/AppleEmptyState\.vue'/)
  assert.match(sourceHealthPanel, /<AppleSkeleton[\s\S]*label="来源状态加载中"/)
  assert.match(sourceHealthPanel, /<AppleEmptyState[\s\S]*:title="sourceHealthEmptyState\.title"[\s\S]*:next-step="sourceHealthEmptyState\.nextStep"/)
  assert.match(sourceHealthPanel, /action-label="刷新来源"/)
  assert.match(sourceHealthPanel, /secondary-action-label="运行诊断"/)
  assert.match(sourceHealthPanel, /@action="\$emit\('refresh-health'\)"/)
  assert.match(sourceHealthPanel, /@secondary-action="\$emit\('run-smoke'\)"/)
})

test('supplement job status pills use semantic layered glass tokens', () => {
  const base = cssBlock(jobList, '.status-pill')
  const succeeded = cssBlock(jobList, '.status-succeeded')
  const running = cssBlock(jobList, '.status-running')
  const queued = cssBlock(jobList, '.status-queued')
  const failed = cssBlock(jobList, '.status-failed')

  assert.match(base, /color:\s*var\(--badge-info-text\)/)
  assertLayeredBackground(base, '--badge-info-bg', 'supplement job default status')
  assert.match(base, /border:\s*1px solid var\(--badge-info-border\)/)

  assert.match(succeeded, /color:\s*var\(--badge-success-text\)/)
  assertLayeredBackground(succeeded, '--badge-success-bg', 'supplement job succeeded status')
  assert.match(succeeded, /border-color:\s*var\(--badge-success-border\)/)

  for (const [block, name] of [
    [running, 'supplement job running status'],
    [queued, 'supplement job queued status'],
  ]) {
    assert.match(block, /color:\s*var\(--badge-warning-text\)/, `${name} should keep warning text`)
    assertLayeredBackground(block, '--badge-warning-bg', name)
    assert.match(block, /border-color:\s*var\(--badge-warning-border\)/, `${name} should keep warning border`)
  }

  assert.match(failed, /color:\s*var\(--badge-error-text\)/)
  assertLayeredBackground(failed, '--badge-error-bg', 'supplement job failed status')
  assert.match(failed, /border-color:\s*var\(--badge-error-border\)/)

  for (const block of [base, succeeded, running, queued, failed]) {
    assert.doesNotMatch(block, /rgba\(255,\s*255,\s*255|#[0-9a-f]{3,6}/i)
  }
})

test('supplement workspace status badges use semantic layered glass tokens', () => {
  const defaultStatus = cssBlock(externalStyle, '.status-pill')
  const succeeded = cssBlock(externalStyle, '.status-succeeded')
  const running = cssBlock(externalStyle, '.status-running')
  const queued = cssBlock(externalStyle, '.status-queued')
  const failed = cssBlock(externalStyle, '.status-failed')
  const idle = cssBlock(externalStyle, '.status-idle')
  const movieDefault = cssBlock(moviesStyle, '.status-pill')
  const matched = cssBlock(moviesStyle, '.match-matched')
  const candidate = cssBlock(moviesStyle, '.match-candidate')
  const supplementOnly = cssBlock(moviesStyle, '.match-supplement-only')
  const ignored = cssBlock(moviesStyle, '.match-ignored')

  for (const [block, label] of [
    [defaultStatus, 'workspace default status'],
    [movieDefault, 'workspace movie default status'],
    [supplementOnly, 'workspace supplement-only match'],
    [idle, 'workspace idle status'],
  ]) {
    assertLayeredBackground(block, '--badge-info-bg', label)
    assert.match(block, /color:\s*var\(--badge-info-text\)/, `${label} should keep info text`)
    assert.match(block, /border(?:-color)?:\s*(?:1px solid )?var\(--badge-info-border\)/, `${label} should keep info border`)
  }

  for (const [block, label] of [
    [succeeded, 'workspace succeeded status'],
    [matched, 'workspace matched status'],
  ]) {
    assertLayeredBackground(block, '--badge-success-bg', label)
    assert.match(block, /color:\s*var\(--badge-success-text\)/, `${label} should keep success text`)
    assert.match(block, /border-color:\s*var\(--badge-success-border\)/, `${label} should keep success border`)
  }

  for (const [block, label] of [
    [running, 'workspace running status'],
    [queued, 'workspace queued status'],
    [candidate, 'workspace candidate match'],
  ]) {
    assertLayeredBackground(block, '--badge-warning-bg', label)
    assert.match(block, /color:\s*var\(--badge-warning-text\)/, `${label} should keep warning text`)
    assert.match(block, /border-color:\s*var\(--badge-warning-border\)/, `${label} should keep warning border`)
  }

  assertLayeredBackground(failed, '--badge-error-bg', 'workspace failed status')
  assert.match(failed, /color:\s*var\(--badge-error-text\)/)
  assert.match(failed, /border-color:\s*var\(--badge-error-border\)/)

  assertLayeredBackground(ignored, '--badge-pending-bg', 'workspace ignored match')
  assert.match(ignored, /color:\s*var\(--badge-pending-text\)/)
  assert.match(ignored, /border-color:\s*var\(--badge-pending-border\)/)
})

test('supplement management exposes provider smoke diagnostics', () => {
  assert.match(sourceHealthPanel, /运行诊断/)
  assert.match(source, /runProviderSmoke/)
  assert.match(source, /api\.runSupplementProviderSmoke\(payload\)/)
  assert.match(source, /providerSmokeForm/)
  assert.match(sourceHealthPanel, /source_movie_id/)
  assert.match(source, /自定义样本需要先选择来源/)
  assert.match(sourceHealthPanel, /最近诊断/)
  assert.match(source, /api\.listSupplementProviderSmokeRuns\(5, this\.providerSmokeForm\.source\)/)
  assert.match(supplementFeatureSource, /smokeRunLabel/)
  assert.match(source, /providerSmokeReport/)
  assert.match(sourceHealthPanel, /字段分/)
})

test('source health panel groups diagnostics into professional repair modes', () => {
  assert.match(sourceHealthPanel, /class="source-health-modebar"/)
  assert.match(sourceHealthPanel, /class="source-health-summary-grid"/)
  assert.match(sourceHealthPanel, /class="health-summary-card"/)
  assert.match(sourceHealthPanel, /class="source-runbook"/)
  assert.match(sourceHealthPanel, /class="source-health-queue-head"/)
  assert.match(sourceHealthPanel, /诊断模式/)
  assert.match(sourceHealthPanel, /恢复模式/)
  assert.match(sourceHealthPanel, /隔离模式/)
  assert.match(sourceHealthPanel, /sourceHealthSummary/)
  assert.match(sourceHealthPanel, /sourceHealthMode/)
  assert.match(sourceHealthPanel, /sourceHealthVisibleRows/)
  assert.match(sourceHealthPanel, /sourceHealthQueueTitle/)
  assert.match(sourceHealthPanel, /sourceHealthQueueHint/)
  assert.match(sourceHealthPanel, /sourceHealthPrimaryAction\(source\)/)
  assert.match(sourceHealthPanel, /event: 'resume-source'/)
  assert.match(sourceHealthPanel, /@click="\$emit\(sourceHealthPrimaryAction\(source\)\.event, source\.source\)"/)
  assert.match(sourceHealthPanel, /解除冷却/)
  assert.match(sourceHealthPanel, /sourceHealthRows\.filter\(source => source\.runtime_status === 'cooling_down' \|\| source\.runtime_status === 'paused'\)/)
  assert.match(sourceHealthPanel, /this\.sourceHealthRows\.filter\(source => \['degraded', 'cooling_down', 'paused'\]\.includes\(source\.runtime_status\)\)/)
  assert.match(sourceHealthPanel, /v-for="source in sourceHealthVisibleRows"/)
  assert.match(sourceHealthPanel, /degradedSources/)
  assert.match(sourceHealthPanel, /pausedSources/)
  assert.match(sourceHealthPanel, /avatarJobRunning/)
  assert.match(sourceHealthPanel, /\.source-health-modebar/)
  assert.match(sourceHealthPanel, /\.source-health-summary-grid/)
  assert.match(sourceHealthPanel, /\.source-health-queue-head/)
})

test('source health styles stay in the lazy child chunk', () => {
  assert.match(source, /const SourceHealthPanel = defineAsyncComponent/)
  assert.match(sourceHealthPanelVue, /<style scoped src="\.\/sourceHealthPanel\.css"><\/style>/)
  assert.doesNotMatch(source, /\.avatar-sync-panel\s*\{/)
  assert.doesNotMatch(source, /\.provider-smoke-summary\s*\{/)
  assert.doesNotMatch(source, /\.provider-smoke-card\s*\{/)
  assert.doesNotMatch(source, /\.provider-smoke-history\s*\{/)
  assert.doesNotMatch(source, /\.provider-smoke-run\s*\{/)
  assert.doesNotMatch(source, /\.source-health-card\s*\{/)
  assert.doesNotMatch(source, /\.source-budget-meter\s*\{/)
})

test('supplement management preserves a global queue entry point', () => {
  assert.match(source, /showGlobalQueue/)
  assert.match(source, /openGlobalQueue\(\)/)
  assert.match(source, /全局队列/)
  assert.match(source, /applyJobActorContext\(job\)/)
})

test('supplement management applies routed global job status filters', () => {
  assert.match(source, /status: field\('status'\)/)
  assert.match(source, /const status = typeof this\.\$route\.query\.status === 'string'/)
  assert.match(source, /this\.jobFilters\.status = status/)
  assert.match(source, /tab === 'jobs'/)
  assert.match(source, /this\.showGlobalQueue = true/)
  assert.match(source, /if \(this\.jobFilters\.status\) params\.status = this\.jobFilters\.status/)
  assert.match(source, /if \(this\.jobFilters\.source\) params\.source = this\.jobFilters\.source/)
  assert.match(source, /await this\.replaceSupplementRoute\(\{[\s\S]*tab: 'jobs'[\s\S]*status: this\.jobFilters\.status/)
  assert.match(source, /await this\.replaceSupplementRoute\(\{[\s\S]*tab: 'jobs'[\s\S]*source: this\.jobFilters\.source/)
})

test('supplement global queue explains routed compound provider filters', () => {
  assert.match(vueSource, /class="queue-filter-summary"/)
  assert.match(vueSource, /v-for="item in globalQueueContextItems"/)
  assert.match(vueSource, /:context-label="globalQueueContextLabel"/)
  assert.match(source, /error_provider: field\('error_provider'\)/)
  assert.match(source, /error_reason: field\('error_reason'\)/)
  assert.match(source, /const errorProvider = typeof this\.\$route\.query\.error_provider === 'string'/)
  assert.match(source, /const errorReason = typeof this\.\$route\.query\.error_reason === 'string'/)
  assert.match(source, /globalQueueSourceLabel\(\)/)
  assert.match(source, /this\.jobFilters\.source === 'all'/)
  assert.match(source, /this\.jobFilters\.error_provider/)
  assert.match(source, /含 \$\{this\.jobFilters\.error_provider\} 的复合失败/)
  assert.match(source, /包含多个来源的复合失败/)
  assert.match(source, /globalQueueContextLabel\(\)/)
  assert.match(source, /globalQueueContextItems\(\)/)
  assert.match(source, /provider: this\.jobFilters\.error_provider/)
  assert.match(source, /reason: this\.jobFilters\.error_reason/)
  assert.match(jobList, /contextLabel/)
  assert.match(jobList, /:description="emptyDescription"/)
  assert.match(jobList, /if \(this\.contextLabel\) return this\.contextLabel/)
  assert.match(externalStyle, /\.queue-filter-summary/)
  assert.match(externalStyle, /\.queue-filter-chip/)
  assert.match(source, /if \(this\.jobFilters\.error_provider\) params\.error_provider = this\.jobFilters\.error_provider/)
  assert.match(source, /if \(this\.jobFilters\.error_reason\) params\.error_reason = this\.jobFilters\.error_reason/)
})

test('supplement management applies routed movie search and resets filtered pages', () => {
  assert.match(source, /const q = typeof this\.\$route\.query\.q === 'string'/)
  assert.match(source, /const quality = typeof this\.\$route\.query\.quality === 'string'/)
  assert.match(source, /this\.movieFilters\.q = q/)
  assert.match(source, /this\.movieFilters\.quality = quality/)
  assert.match(source, /this\.moviePage = 1/)
  assert.match(source, /@apply-filters="applyMovieFilters"/)
  assert.match(moviesPanel, /@change="\$emit\('apply-filters'\)"/)
  assert.match(moviesPanel, /@keyup\.enter="\$emit\('apply-filters'\)"/)
  assert.match(source, /async applyMovieFilters\(\)[\s\S]*this\.moviePage = 1[\s\S]*await this\.loadMovies\(\)/)
  assert.match(source, /@change="applyJobFilters"/)
  assert.match(source, /async applyJobFilters\(\)[\s\S]*this\.jobPage = 1[\s\S]*await this\.loadJobs\(\)/)
  assert.match(source, /if \(this\.movieFilters\.q\) query\.q = this\.movieFilters\.q/)
  assert.match(source, /if \(this\.movieFilters\.quality\) query\.quality = this\.movieFilters\.quality/)
})

test('supplement management normalizes hard panel routes into workspace tabs', () => {
  assert.match(source, /isSupplementRoute\(\)/)
  assert.match(source, /supplementRouteTab\(\)/)
  assert.match(source, /this\.\$route\.path\.startsWith\('\/supplement\/'\)/)
  assert.match(source, /if \(this\.\$route\.path === '\/supplement\/movies'\) return 'movies'/)
  assert.match(source, /if \(this\.\$route\.path === '\/supplement\/jobs'\) return 'jobs'/)
  assert.match(source, /if \(this\.\$route\.path === '\/supplement\/sources'\) return 'sources'/)
  assert.match(source, /if \(this\.\$route\.path === '\/supplement\/stats'\) return 'stats'/)
  assert.match(source, /if \(!this\.isSupplementRoute\(\)\) return/)
  assert.match(source, /const tab = this\.supplementRouteTab\(\)/)
  assert.match(source, /this\.\$route\.path === '\/supplement' && this\.supplementQueryKey\(nextQuery\) === this\.supplementQueryKey\(\)/)
  assert.doesNotMatch(source, /this\.\$route\.path !== '\/supplement'/)
})

test('supplement management opens global movie repair from data quality routes', () => {
  assert.match(source, /showGlobalMovieRepair/)
  assert.match(source, /v-else-if="showGlobalMovieRepair"/)
  assert.match(source, /activeWorkspaceSegment === 'movies' \|\| showGlobalMovieRepair/)
  assert.match(source, /tab === 'movies' && quality/)
  assert.match(source, /this\.showGlobalMovieRepair = true/)
  assert.match(source, /await this\.loadMovies\(\)/)
  assert.match(source, /this\.showGlobalMovieRepair = false/)
})

test('supplement management refreshes workspace data when supplement polling finishes', () => {
  assert.match(source, /async refreshSupplementWorkspaceAfterPolling\(\)/)
  assert.match(source, /await this\.refreshSupplementWorkspaceAfterPolling\(\)/)
  assert.match(source, /Promise\.all\(\[[\s\S]*this\.loadJobs\(\{ silent: true \}\)[\s\S]*this\.loadMovies\(\{ silent: true \}\)[\s\S]*this\.loadSupplementStatus\(\{ poll: false \}\)/)
})

test('supplement management creates download candidates from current movie filters', () => {
  assert.match(source, /buildMovieFilterParams\(/)
  assert.match(source, /if \(this\.movieFilters\.matched !== null\) params\.matched = this\.movieFilters\.matched/)
  assert.match(source, /if \(this\.movieFilters\.quality === 'missing_cover'\) params\.missing_cover = true/)
  assert.match(source, /if \(this\.movieFilters\.quality === 'missing_runtime'\) params\.missing_runtime = true/)
  assert.match(source, /if \(this\.movieFilters\.quality === 'missing_maker'\) params\.missing_maker = true/)
  assert.match(source, /if \(this\.movieFilters\.quality === 'missing_categories'\) params\.missing_categories = true/)
  assert.match(source, /if \(this\.movieFilters\.quality === 'low_completeness'\) params\.max_completeness = 2/)
  assert.match(source, /const params = this\.buildMovieFilterParams\(\)/)
  assert.doesNotMatch(source, /buildMovieFilterParams\(\{ limit: 100 \}\)/)
  assert.match(source, /if \(this\.actorContextName\) params\.actress_name = this\.actorContextName/)
})

test('supplement management avoids a remount-style refresh when re-entered', () => {
  assert.match(app, /'SupplementManagement'/)
  assert.match(source, /activated\(\)/)
  assert.match(source, /wasDeactivated/)
  assert.match(source, /lastAppliedRouteKey/)
  assert.match(source, /replaceSupplementRoute/)
  assert.doesNotMatch(source, /class="supplement-page apple-reveal"/)
})

test('supplement actor picker keeps search glass in the lazy child', () => {
  const pickerSearch = cssBlock(actorPicker, '.search-shell')
  const pickerSearchFocus = cssBlock(actorPicker, '.search-shell:focus-within')

  assert.doesNotMatch(actorPicker, /var\(--surface-control\)|var\(--surface-input-focus\)|var\(--active-border\)/)
  assertLayeredBackground(pickerSearch, '--material-glass-control', 'actor picker search')
  assert.match(pickerSearch, /border:\s*1px solid var\(--glass-control-border\)/)
  assert.match(pickerSearch, /box-shadow:\s*var\(--glass-control-shadow\)/)
  assert.match(pickerSearch, /backdrop-filter:\s*blur\(var\(--glass-blur-control\)\)\s*saturate\(var\(--glass-saturate-control\)\)/)
  assert.match(pickerSearchFocus, /border-color:\s*var\(--glass-active-border\)/)
  assertLayeredBackground(pickerSearchFocus, '--glass-active-material', 'actor picker focused search')
  assert.match(pickerSearchFocus, /box-shadow:\s*var\(--glass-active-shadow\)/)
  assert.doesNotMatch(actorPicker, /^.*background:\s*var\(--(?:material-glass-control|glass-active-material)\);.*$/gm)

  assert.doesNotMatch(source, /\.supplement-hero\s*\{/)
  assert.doesNotMatch(source, /\.actor-filter-bar\s*\{/)
  assert.doesNotMatch(source, /\.compact-search\s*\{/)
  assert.doesNotMatch(source, /\.actor-result-card\s*,/)
  assert.doesNotMatch(source, /\.recent-actor-row\s*\{/)
  assert.doesNotMatch(source, /\.recent-actor-list\s*\{/)
})

test('supplement workspace rows and filters use shared Apple glass controls', () => {
  const input = cssBlock(moviesStyle, '.filter-input')
  const inputFocus = cssBlock(moviesStyle, '.filter-input:focus')
  const movieRow = cssBlock(moviesStyle, '.ios-row')
  const jobRow = cssBlock(jobList, '.ios-row')
  const jobRowHover = cssBlock(jobList, '.ios-row:hover')
  const jobRowFocusWithin = cssBlock(jobList, '.ios-row:focus-within')
  const workspaceAvatar = cssBlock(externalStyle, '.workspace-avatar')
  const jobAvatar = cssBlock(jobList, '.job-avatar')
  const emptyInner = cssBlock(externalStyle, '.empty-panel.inner')

  assert.doesNotMatch(source, /var\(--surface-card\)|var\(--surface-control\)|var\(--surface-control-hover\)|var\(--surface-input-focus\)|var\(--bg-secondary\)|var\(--white-20\)|rgba\(255,\s*107,\s*135|#ff6b87|var\(--active-border\)/)
  assert.doesNotMatch(jobList, /var\(--surface-control\)|var\(--bg-secondary\)|var\(--white-20\)/)

  assertLayeredBackground(input, '--material-glass-control', 'supplement filter input')
  assert.match(input, /border:\s*1px solid var\(--glass-control-border\)/)
  assert.match(input, /box-shadow:\s*var\(--glass-control-shadow\)/)
  assert.match(input, /backdrop-filter:\s*blur\(var\(--glass-blur-control\)\)\s*saturate\(var\(--glass-saturate-control\)\)/)
  assert.match(inputFocus, /border-color:\s*var\(--glass-active-border\)/)
  assertLayeredBackground(inputFocus, '--glass-active-material', 'supplement focused filter input')
  assert.match(inputFocus, /box-shadow:\s*var\(--glass-active-shadow\)/)
  assert.doesNotMatch([input, inputFocus].join('\n'), /^.*background:\s*var\(--(?:material-glass-control|glass-active-material)\);.*$/gm)

  for (const block of [movieRow, jobRow]) {
    assertLayeredBackground(block, '--material-glass-control', 'supplement workspace row')
    assert.match(block, /border:\s*1px solid var\(--glass-control-border\)/)
    assert.match(block, /box-shadow:\s*var\(--glass-control-shadow\)/)
    assert.match(block, /backdrop-filter:\s*blur\(var\(--glass-blur-control\)\)\s*saturate\(var\(--glass-saturate-control\)\)/)
  }
  assertLayeredBackground(emptyInner, '--material-glass-control', 'supplement inner empty panel')
  assert.match(emptyInner, /border:\s*1px solid var\(--glass-control-border\)/)
  assert.match(emptyInner, /box-shadow:\s*var\(--glass-control-shadow\)/)
  assert.match(emptyInner, /backdrop-filter:\s*blur\(var\(--glass-blur-control\)\)\s*saturate\(var\(--glass-saturate-control\)\)/)
  assert.doesNotMatch([movieRow, jobRow, emptyInner].join('\n'), /^.*background:\s*var\(--material-glass-control\);.*$/gm)

  assertLayeredBackground(jobRow, '--material-glass-control', 'supplement job row')
  assert.match(jobRow, /border:\s*1px solid var\(--glass-control-border\)/)
  assert.match(jobRow, /box-shadow:\s*var\(--glass-control-shadow\)/)
  assert.match(jobRow, /transition:\s*transform var\(--motion-fast\),\s*opacity var\(--motion-fast\)/)
  assert.doesNotMatch(jobRow, /transition:[^;]*(?:background|border-color|box-shadow|color|filter|backdrop-filter)/)
  assert.match(jobRow, /backdrop-filter:\s*blur\(var\(--glass-blur-control\)\)\s*saturate\(var\(--glass-saturate-control\)\)/)
  assert.doesNotMatch(jobList, /^.*background:\s*var\(--material-glass-control\);.*$/gm)

  assertLayeredBackground(jobRowHover, '--material-glass-control-hover', 'supplement hovered job row')
  assert.match(jobRowHover, /border-color:\s*var\(--glass-control-border-hover\)/)
  assert.match(jobRowHover, /box-shadow:\s*var\(--glass-control-shadow-hover\)/)
  assert.match(jobRowHover, /transform:\s*translateY\(-1px\)/)
  assertLayeredBackground(jobRowFocusWithin, '--material-glass-control-hover', 'supplement focused job row')
  assert.match(jobRowFocusWithin, /border-color:\s*var\(--glass-control-border-hover\)/)
  assert.match(jobRowFocusWithin, /box-shadow:\s*var\(--glass-control-shadow-hover\),\s*var\(--focus-ring\)/)
  assert.match(jobRowFocusWithin, /transform:\s*translateY\(-1px\)/)
  assert.doesNotMatch([jobRowHover, jobRowFocusWithin].join('\n'), /^.*background:\s*var\(--material-glass-control-hover\);.*$/gm)

  const avatarBlocks = [workspaceAvatar, jobAvatar]
  for (const block of avatarBlocks) {
    assertLayeredBackground(block, '--material-glass-subtle', 'supplement workspace avatar')
    assert.match(block, /border:\s*1px solid var\(--glass-control-border\)/)
    assert.match(block, /box-shadow:\s*var\(--glass-inner-shadow\)/)
    assert.match(block, /backdrop-filter:\s*blur\(var\(--glass-blur-control\)\)\s*saturate\(var\(--glass-saturate-control\)\)/)
  }
  assert.doesNotMatch(avatarBlocks.join('\n'), /^.*background:\s*var\(--material-glass-subtle\);.*$/gm)

  assert.match(moviesPanel, /<AppleSkeleton[\s\S]*label="补全影片加载中"/)
  assert.match(jobList, /<AppleSkeleton[\s\S]*label="补全任务加载中"/)
  assert.doesNotMatch(`${moviesPanel}\n${jobList}`, /<div[^>]+class="loading-wrap"[\s\S]{0,120}<div class="spinner-large"><\/div>/)
})

test('supplement diagnostics modal opens as a triage workbench', () => {
  assert.match(vueSource, /class="diagnostics-inline-state"/)
  assert.match(vueSource, /正在查看诊断/)
  assert.match(vueSource, /diagnosticsMovieTitle/)
  assert.match(diagnosticsDialog, /class="diagnostics-triage"/)
  assert.match(diagnosticsDialog, /class="triage-card"/)
  assert.match(diagnosticsDialog, /class="diagnostics-layout"/)
  assert.match(diagnosticsDialog, /class="manual-match-panel"/)
  assert.match(diagnosticsDialog, /class="candidate-decision-strip"/)
  assert.match(diagnosticsDialog, /candidateDecisionCards/)
  assert.match(diagnosticsDialog, /topCandidate/)
  assert.match(diagnosticsDialog, /candidateScoreGap/)
  assert.match(diagnosticsDialog, /v-for="candidate in sortedCandidates"/)
  assert.match(diagnosticsDialog, /candidateRowClass\(candidate\)/)
  assert.match(diagnosticsDialog, /candidateDecisionLabel\(candidate\)/)
  assert.match(diagnosticsDialog, /首选/)
  assert.match(diagnosticsDialog, /复核/)
  assert.match(diagnosticsDialog, /首选候选/)
  assert.match(diagnosticsDialog, /分差/)
  assert.match(diagnosticsDialog, /确认风险/)
  assert.match(diagnosticsDialog, /class="diagnostics-action-queue"/)
  assert.match(diagnosticsDialog, /class="diagnostics-action-item"/)
  assert.match(diagnosticsDialog, /diagnosticsActionItemClass\(action\)/)
  assert.match(diagnosticsDialog, /diagnosticsActionQueue/)
  assert.match(diagnosticsDialog, /diagnosticsTriageCards/)
  assert.match(diagnosticsDialog, /missingFieldCount/)
  assert.match(diagnosticsDialog, /diagnosticsFieldChecklist/)
  assert.match(diagnosticsDialog, /missingDiagnosticsFields/)
  assert.match(diagnosticsDialog, /class="diagnostics-field-source-matrix"/)
  assert.match(diagnosticsDialog, /fieldSourceRepairRows/)
  assert.match(diagnosticsDialog, /fieldSourceCoverage\(field\)/)
  assert.match(diagnosticsDialog, /fieldSourceRepairClass\(row\)/)
  assert.match(diagnosticsDialog, /fieldHasDiagnosticValue/)
  assert.match(diagnosticsDialog, /class="diagnostics-field-work-orders"/)
  assert.match(diagnosticsDialog, /v-for="order in fieldRepairWorkOrders"/)
  assert.match(diagnosticsDialog, /class="field-work-order"/)
  assert.match(diagnosticsDialog, /fieldRepairWorkOrders/)
  assert.match(diagnosticsDialog, /fieldWorkOrderClass\(order\)/)
  assert.match(diagnosticsDialog, /fieldCurrentSourceLabel\(field\)/)
  assert.match(diagnosticsDialog, /fieldRepairActionLabel\(field\)/)
  assert.match(diagnosticsDialog, /当前来源/)
  assert.match(diagnosticsDialog, /可补渠道/)
  assert.match(diagnosticsDialog, /修复动作/)
  assert.match(diagnosticsDialog, /label_name/)
  assert.match(diagnosticsDialog, /series_name/)
  assert.match(diagnosticsDialog, /category_names/)
  assert.match(diagnosticsDialog, /genres/)
  assert.match(diagnosticsDialog, /candidateCount/)
  assert.match(diagnosticsDialog, /identityCount/)
  assert.match(diagnosticsDialog, /字段缺口/)
  assert.match(diagnosticsDialog, /补字段/)
  assert.match(diagnosticsDialog, /确认匹配/)
  assert.match(diagnosticsDialog, /补源身份/)
  assert.match(diagnosticsDialog, /可入库/)
  assert.match(diagnosticsDialog, /高优先级/)
  assert.match(diagnosticsDialog, /待处理/)
  assert.match(diagnosticsDialog, /已就绪/)
  assert.match(diagnosticsDialog, /action\.priority/)
  assert.match(diagnosticsDialog, /action\.tone/)
  assert.match(diagnosticsDialog, /action\.status/)
  assert.match(diagnosticsDialog, /字段来源矩阵/)
  assert.match(diagnosticsDialog, /影片本体/)
  assert.match(diagnosticsDialog, /已选字段/)
  assert.match(diagnosticsDialog, /详情来源/)
  assert.match(diagnosticsDialog, /缺口/)
  assert.match(diagnosticsDialog, /可用/)
  assert.match(diagnosticsStyle, /\.diagnostics-triage/)
  assert.match(diagnosticsStyle, /\.diagnostics-layout/)
  assert.match(diagnosticsStyle, /\.manual-match-panel/)
  assert.match(diagnosticsStyle, /\.candidate-decision-strip/)
  assert.match(diagnosticsStyle, /\.candidate-decision-card/)
  assert.match(diagnosticsStyle, /\.candidate-row-primary/)
  assert.match(diagnosticsStyle, /\.candidate-row-review/)
  assert.match(diagnosticsStyle, /\.candidate-row-decision/)
  assert.match(diagnosticsStyle, /\.diagnostics-action-queue/)
  assert.match(diagnosticsStyle, /\.diagnostics-action-item/)
  assert.match(diagnosticsStyle, /\.diagnostics-action-item\.danger/)
  assert.match(diagnosticsStyle, /\.diagnostics-action-item\.warning/)
  assert.match(diagnosticsStyle, /\.diagnostics-action-item\.ready/)
  assert.match(diagnosticsStyle, /\.diagnostics-action-priority/)
  assert.match(diagnosticsStyle, /\.diagnostics-field-source-matrix/)
  assert.match(diagnosticsStyle, /\.field-source-row/)
  assert.match(diagnosticsStyle, /\.field-source-row\.missing/)
  assert.match(diagnosticsStyle, /\.field-source-status/)
  assert.match(diagnosticsStyle, /\.field-source-pill\.ready/)
  assert.match(diagnosticsStyle, /\.diagnostics-field-work-orders/)
  assert.match(diagnosticsStyle, /\.field-work-order/)
  assert.match(diagnosticsStyle, /\.field-work-order\.missing/)
  assert.match(diagnosticsStyle, /\.field-work-order\.ready/)
  assert.match(diagnosticsStyle, /\.field-work-order-lane/)
  assert.match(diagnosticsStyle, /\.field-work-order-status/)
  assert.match(externalStyle, /\.diagnostics-inline-state/)

  const fieldWorkOrder = cssBlock(diagnosticsStyle, '.field-work-order')
  const fieldWorkOrderLaneBlocks = [...diagnosticsStyle.matchAll(/([^{}]+)\{([^{}]*)\}/g)]
    .filter(([, selectors]) => selectors
      .split(',')
      .map(part => part.trim())
      .includes('.field-work-order-lane'))
    .map(([, , block]) => block)
  assert.match(fieldWorkOrder, /min-height:\s*88px/)
  assert.ok(
    fieldWorkOrderLaneBlocks.every(block => /grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\)/.test(block)),
    'field work order lane should stay three compact columns at all breakpoints',
  )
})

test('supplement diagnostics modal surfaces a dense field command strip', () => {
  assert.match(diagnosticsDialog, /class="diagnostics-command-console"/)
  assert.match(diagnosticsDialog, /aria-label="诊断操作控制台"/)
  assert.match(diagnosticsDialog, /class="diagnostics-command-summary"/)
  assert.match(diagnosticsDialog, /class="diagnostics-command-lanes"/)
  assert.match(diagnosticsDialog, /v-for="lane in diagnosticsCommandLanes"/)
  assert.match(diagnosticsDialog, /class="diagnostics-command-lane"/)
  assert.match(diagnosticsDialog, /diagnosticsCommandLaneClass\(lane\)/)
  assert.match(diagnosticsDialog, /diagnosticsCommandLanes/)
  assert.match(diagnosticsDialog, /diagnosticsCommandTotal/)
  assert.match(diagnosticsDialog, /diagnosticsCommandPrimary/)
  assert.match(diagnosticsDialog, /fieldRepairWorkOrders\.filter\(order => !order\.ready\)\.length/)
  assert.match(diagnosticsDialog, /candidateConfirmationRisk === '需人工复核'/)
  assert.match(diagnosticsDialog, /missingFieldCount === 0 && identityCount > 0/)
  assert.match(diagnosticsDialog, /操作控制台/)
  assert.match(diagnosticsDialog, /待修字段/)
  assert.match(diagnosticsDialog, /匹配复核/)
  assert.match(diagnosticsDialog, /入库门槛/)
  assert.match(diagnosticsDialog, /先补字段/)
  assert.match(diagnosticsDialog, /复核候选/)
  assert.match(diagnosticsDialog, /检查身份/)
  assert.match(diagnosticsDialog, /class="diagnostics-field-command-strip"/)
  assert.match(diagnosticsDialog, /class="field-command-summary"/)
  assert.match(diagnosticsDialog, /class="field-command-grid"/)
  assert.match(diagnosticsDialog, /v-for="command in diagnosticsFieldCommands"/)
  assert.match(diagnosticsDialog, /class="diagnostics-field-command"/)
  assert.match(diagnosticsDialog, /fieldCommandClass\(command\)/)
  assert.match(diagnosticsDialog, /diagnosticsFieldCommands\(\)/)
  assert.match(diagnosticsDialog, /fieldCommandPriority\(order\)/)
  assert.match(diagnosticsDialog, /fieldCommandSourceSignal\(order\)/)
  assert.match(diagnosticsDialog, /字段指挥台/)
  assert.match(diagnosticsDialog, /优先字段/)
  assert.match(diagnosticsDialog, /来源信号/)
  assert.match(diagnosticsDialog, /下一步/)
  assert.match(diagnosticsDialog, /字段已齐/)
  assert.match(diagnosticsDialog, /等待来源采样/)
  assert.match(diagnosticsDialog, /slice\(0, 4\)/)
  assert.match(diagnosticsStyle, /\.diagnostics-field-command-strip/)
  assert.match(diagnosticsStyle, /\.diagnostics-command-console/)
  assert.match(diagnosticsStyle, /\.diagnostics-command-summary/)
  assert.match(diagnosticsStyle, /\.diagnostics-command-lanes/)
  assert.match(diagnosticsStyle, /\.diagnostics-command-lane/)
  assert.match(diagnosticsStyle, /\.diagnostics-command-lane\.danger/)
  assert.match(diagnosticsStyle, /\.diagnostics-command-lane\.warning/)
  assert.match(diagnosticsStyle, /\.diagnostics-command-lane\.ready/)
  assert.match(diagnosticsStyle, /\.field-command-summary/)
  assert.match(diagnosticsStyle, /\.field-command-grid/)
  assert.match(diagnosticsStyle, /\.diagnostics-field-command/)
  assert.match(diagnosticsStyle, /\.diagnostics-field-command\.missing/)
  assert.match(diagnosticsStyle, /\.diagnostics-field-command\.ready/)
  assert.match(diagnosticsStyle, /\.field-command-source/)
  assert.match(diagnosticsStyle, /\.field-command-next/)

  const commandStrip = cssBlock(diagnosticsStyle, '.diagnostics-field-command-strip')
  const commandConsole = cssBlock(diagnosticsStyle, '.diagnostics-command-console')
  const commandLanes = cssBlock(diagnosticsStyle, '.diagnostics-command-lanes')
  const commandLane = cssBlock(diagnosticsStyle, '.diagnostics-command-lane')
  const commandGrid = cssBlock(diagnosticsStyle, '.field-command-grid')
  const commandCard = cssBlock(diagnosticsStyle, '.diagnostics-field-command')
  assertLayeredBackground(commandConsole, '--material-glass-sheet', 'diagnostics command console')
  assert.match(commandConsole, /grid-template-columns:\s*minmax\(150px,\s*0\.22fr\)\s*minmax\(0,\s*1fr\)/)
  assert.match(commandLanes, /grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\)/)
  assertLayeredBackground(commandLane, '--material-glass-control', 'diagnostics command lane')
  assert.match(commandLane, /min-width:\s*0/)
  assert.match(commandLane, /overflow-wrap:\s*anywhere/)
  assertLayeredBackground(commandStrip, '--material-glass-sheet', 'diagnostics field command strip')
  assert.match(commandGrid, /grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(commandCard, /min-width:\s*0/)
  assert.match(commandCard, /overflow-wrap:\s*anywhere/)
})

test('supplement diagnostics modal avoids legacy flat surfaces', () => {
  const header = cssBlock(source, '.diagnostics-header')
  const table = cssBlock(source, '.diagnostics-table')
  const row = cssBlock(source, '.diagnostics-row')
  const headRow = cssBlock(source, '.diagnostics-row-head')
  const identityChip = cssBlock(source, '.identity-chip')
  const detailSourceItem = cssBlock(source, '.detail-source-item')
  const manualAction = cssBlock(source, '.manual-action-item')

  assertLayeredBackground(header, '--material-glass-sheet', 'supplement diagnostics header')
  assert.match(header, /border-bottom:\s*1px solid var\(--glass-control-border\)/)
  assert.match(header, /box-shadow:\s*var\(--glass-surface-shadow\)/)
  assert.match(header, /backdrop-filter:\s*blur\(var\(--glass-blur-surface\)\)\s*saturate\(var\(--glass-saturate-surface\)\)/)

  assert.match(table, /border:\s*1px solid var\(--glass-control-border\)/)
  assert.match(table, /box-shadow:\s*var\(--glass-control-shadow\)/)
  assertLayeredBackground(table, '--material-glass-control', 'supplement diagnostics table')
  assert.doesNotMatch([header, table].join('\n'), /^.*background:\s*var\(--(?:material-glass-sheet|material-glass-control)\);.*$/gm)

  const diagnosticsItemBlocks = [row, identityChip, detailSourceItem, manualAction]
  for (const block of diagnosticsItemBlocks) {
    assertLayeredBackground(block, '--material-glass-control', 'supplement diagnostics item')
    assert.match(block, /border:\s*1px solid var\(--glass-control-border\)/)
    assert.match(block, /box-shadow:\s*var\(--glass-control-shadow\)/)
    assert.match(block, /backdrop-filter:\s*blur\(var\(--glass-blur-control\)\)\s*saturate\(var\(--glass-saturate-control\)\)/)
  }
  assert.doesNotMatch(diagnosticsItemBlocks.join('\n'), /^.*background:\s*var\(--material-glass-control\);.*$/gm)

  assertLayeredBackground(headRow, '--glass-active-material', 'supplement diagnostics header row')
  assert.match(headRow, /box-shadow:\s*var\(--glass-active-shadow\)/)
  assert.doesNotMatch(headRow, /^.*background:\s*var\(--glass-active-material\);.*$/gm)
  assert.doesNotMatch(diagnosticsStyle, /\.btn\.danger\s*\{/, 'danger buttons should use the global glass button treatment')
  assert.doesNotMatch(diagnosticsStyle, /#ff6b87|rgba\(255,\s*107,\s*135/i)
})

test('supplement source diagnostics use shared Apple glass materials', () => {
  const diagnosticsOverlay = cssBlock(diagnosticsStyle, '.diagnostics-overlay')
  const input = cssBlock(sourceHealthPanel, '.filter-input')
  const inputFocus = cssBlock(sourceHealthPanel, '.filter-input:focus')
  const avatarPanel = cssBlock(sourceHealthPanel, '.avatar-sync-panel')
  const avatarMetric = cssBlock(sourceHealthPanel, '.avatar-sync-metrics div')
  const smokeSummary = cssBlock(sourceHealthPanel, '.provider-smoke-summary')
  const smokeHistory = cssBlock(sourceHealthPanel, '.provider-smoke-history')
  const smokeRun = cssBlock(sourceHealthPanel, '.provider-smoke-run')
  const smokeRunHover = cssBlock(sourceHealthPanel, '.provider-smoke-run:hover')
  const smokeCard = cssBlock(sourceHealthPanel, '.provider-smoke-card')
  const smokeCardFailed = cssBlock(sourceHealthPanel, '.provider-smoke-card.failed')
  const sourceCard = cssBlock(sourceHealthPanel, '.source-health-card')
  const budgetMeter = cssBlock(sourceHealthPanel, '.source-budget-meter')
  const miniSpinner = cssBlock(sourceHealthPanel, '.mini-spinner')

  assert.doesNotMatch(sourceHealthPanel, /var\(--surface-card\)|var\(--surface-control\)|var\(--surface-control-hover\)|var\(--surface-input-focus\)|var\(--white-20\)|rgba\(255,\s*107,\s*135/)
  assert.match(diagnosticsOverlay, /z-index:\s*var\(--z-modal\)/)
  assert.match(diagnosticsOverlay, /background:\s*var\(--surface-scrim\)/)
  assert.match(diagnosticsOverlay, /backdrop-filter:\s*blur\(var\(--glass-blur-control\)\)\s*saturate\(var\(--glass-saturate-control\)\)/)
  assert.doesNotMatch(diagnosticsOverlay, /z-index:\s*\d+|rgba\(0,\s*0,\s*0/)

  assertLayeredBackground(input, '--material-glass-control', 'supplement source filter input')
  assert.match(input, /border:\s*1px solid var\(--glass-control-border\)/)
  assert.match(input, /box-shadow:\s*var\(--glass-control-shadow\)/)
  assert.match(input, /backdrop-filter:\s*blur\(var\(--glass-blur-control\)\)\s*saturate\(var\(--glass-saturate-control\)\)/)
  assert.match(inputFocus, /border-color:\s*var\(--glass-active-border\)/)
  assertLayeredBackground(inputFocus, '--glass-active-material', 'supplement source focused filter input')
  assert.match(inputFocus, /box-shadow:\s*var\(--glass-active-shadow\)/)
  assert.doesNotMatch([input, inputFocus].join('\n'), /^.*background:\s*var\(--(?:material-glass-control|glass-active-material)\);.*$/gm)

  for (const block of [avatarPanel, smokeSummary, smokeHistory, sourceCard]) {
    assertLayeredBackground(block, '--material-glass-sheet', 'supplement source sheet')
    assert.match(block, /border:\s*1px solid var\(--glass-control-border\)/)
    assert.match(block, /box-shadow:\s*var\(--glass-surface-shadow\)/)
    assert.match(block, /backdrop-filter:\s*blur\(var\(--glass-blur-surface\)\)\s*saturate\(var\(--glass-saturate-surface\)\)/)
  }
  assert.doesNotMatch([avatarPanel, smokeSummary, smokeHistory, sourceCard].join('\n'), /^.*background:\s*var\(--material-glass-sheet\);.*$/gm)

  for (const block of [avatarMetric, smokeRun, smokeCard, budgetMeter]) {
    assertLayeredBackground(block, '--material-glass-control', 'supplement source control')
    assert.match(block, /border:\s*1px solid var\(--glass-control-border\)/)
    assert.match(block, /box-shadow:\s*var\(--glass-control-shadow\)/)
    assert.match(block, /backdrop-filter:\s*blur\(var\(--glass-blur-control\)\)\s*saturate\(var\(--glass-saturate-control\)\)/)
  }
  assert.doesNotMatch([avatarMetric, smokeRun, smokeCard, budgetMeter].join('\n'), /^.*background:\s*var\(--material-glass-control\);.*$/gm)

  assertLayeredBackground(smokeRunHover, '--material-glass-control-hover', 'supplement source hovered run')
  assert.match(smokeRunHover, /border-color:\s*var\(--glass-control-border-hover\)/)
  assert.match(smokeRunHover, /box-shadow:\s*var\(--glass-control-shadow-hover\)/)
  assert.doesNotMatch(smokeRunHover, /^.*background:\s*var\(--material-glass-control-hover\);.*$/gm)
  assert.match(smokeCardFailed, /border-color:\s*var\(--badge-error-border\)/)

  assert.match(sourceHealthPanel, /<AppleSkeleton[\s\S]*label="来源状态加载中"/)
  assert.doesNotMatch(sourceHealthPanel, /<div[^>]+class="loading-wrap"[\s\S]{0,120}<div class="spinner-large"><\/div>/)
  assert.match(miniSpinner, /border:\s*2px solid var\(--glass-control-border\)/)
  assert.match(miniSpinner, /border-top-color:\s*var\(--badge-info-text\)/)
})

test('supplement source status pills use shared semantic badge tokens', () => {
  const idle = cssBlock(sourceHealthPanel, '.status-idle')
  const healthy = cssBlock(sourceHealthPanel, '.health-healthy')
  const degraded = cssBlock(sourceHealthPanel, '.health-degraded')
  const coolingDown = cssBlock(sourceHealthPanel, '.health-cooling_down')
  const paused = cssBlock(sourceHealthPanel, '.health-paused')

  assert.match(idle, /color:\s*var\(--badge-pending-text\)/)
  assertLayeredBackground(idle, '--badge-pending-bg', 'source idle status')
  assert.match(idle, /border-color:\s*var\(--badge-pending-border\)/)

  assert.match(healthy, /color:\s*var\(--badge-success-text\)/)
  assertLayeredBackground(healthy, '--badge-success-bg', 'source healthy status')
  assert.match(healthy, /border-color:\s*var\(--badge-success-border\)/)

  assert.match(degraded, /color:\s*var\(--badge-warning-text\)/)
  assertLayeredBackground(degraded, '--badge-warning-bg', 'source degraded status')
  assert.match(degraded, /border-color:\s*var\(--badge-warning-border\)/)

  assert.match(coolingDown, /color:\s*var\(--badge-error-text\)/)
  assertLayeredBackground(coolingDown, '--badge-error-bg', 'source cooling down status')
  assert.match(coolingDown, /border-color:\s*var\(--badge-error-border\)/)

  assert.match(paused, /color:\s*var\(--badge-pending-text\)/)
  assertLayeredBackground(paused, '--badge-pending-bg', 'source paused status')
  assert.match(paused, /border-color:\s*var\(--badge-pending-border\)/)

  for (const block of [idle, healthy, degraded, coolingDown, paused]) {
    assert.doesNotMatch(block, /rgba\(255,\s*255,\s*255|#[0-9a-f]{3,6}/i)
  }
})
